// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: codespace/v1/service.proto

package codespacev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_codespace_v1_service_proto protoreflect.FileDescriptor

const file_codespace_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1acodespace/v1/service.proto\x12\fcodespace.v1\x1a\x18codespace/v1/types.proto2\x88\b\n" +
	"\x10CodespaceService\x12^\n" +
	"\x0fRegisterManager\x12$.codespace.v1.RegisterManagerRequest\x1a%.codespace.v1.RegisterManagerResponse\x12[\n" +
	"\x0eDeclareManager\x12#.codespace.v1.DeclareManagerRequest\x1a$.codespace.v1.DeclareManagerResponse\x12=\n" +
	"\x04Ping\x12\x19.codespace.v1.PingRequest\x1a\x1a.codespace.v1.PingResponse\x12L\n" +
	"\tFetchTask\x12\x1e.codespace.v1.FetchTaskRequest\x1a\x1f.codespace.v1.FetchTaskResponse\x12L\n" +
	"\tAppendLog\x12\x1e.codespace.v1.AppendLogRequest\x1a\x1f.codespace.v1.AppendLogResponse\x12O\n" +
	"\n" +
	"FinishTask\x12\x1f.codespace.v1.FinishTaskRequest\x1a .codespace.v1.FinishTaskResponse\x12p\n" +
	"\x15ReportCodespaceStatus\x12*.codespace.v1.ReportCodespaceStatusRequest\x1a+.codespace.v1.ReportCodespaceStatusResponse\x12m\n" +
	"\x14ReportCodespacePorts\x12).codespace.v1.ReportCodespacePortsRequest\x1a*.codespace.v1.ReportCodespacePortsResponse\x12^\n" +
	"\x0fRequestGitToken\x12$.codespace.v1.RequestGitTokenRequest\x1a%.codespace.v1.RequestGitTokenResponse\x12[\n" +
	"\x0eRevokeGitToken\x12#.codespace.v1.RevokeGitTokenRequest\x1a$.codespace.v1.RevokeGitTokenResponse\x12m\n" +
	"\x14ValidateAccessTicket\x12).codespace.v1.ValidateAccessTicketRequest\x1a*.codespace.v1.ValidateAccessTicketResponseB7Z5gitea.dev/codespace-proto-go/codespace/v1;codespacev1b\x06proto3"

var file_codespace_v1_service_proto_goTypes = []any{
	(*RegisterManagerRequest)(nil),        // 0: codespace.v1.RegisterManagerRequest
	(*DeclareManagerRequest)(nil),         // 1: codespace.v1.DeclareManagerRequest
	(*PingRequest)(nil),                   // 2: codespace.v1.PingRequest
	(*FetchTaskRequest)(nil),              // 3: codespace.v1.FetchTaskRequest
	(*AppendLogRequest)(nil),              // 4: codespace.v1.AppendLogRequest
	(*FinishTaskRequest)(nil),             // 5: codespace.v1.FinishTaskRequest
	(*ReportCodespaceStatusRequest)(nil),  // 6: codespace.v1.ReportCodespaceStatusRequest
	(*ReportCodespacePortsRequest)(nil),   // 7: codespace.v1.ReportCodespacePortsRequest
	(*RequestGitTokenRequest)(nil),        // 8: codespace.v1.RequestGitTokenRequest
	(*RevokeGitTokenRequest)(nil),         // 9: codespace.v1.RevokeGitTokenRequest
	(*ValidateAccessTicketRequest)(nil),   // 10: codespace.v1.ValidateAccessTicketRequest
	(*RegisterManagerResponse)(nil),       // 11: codespace.v1.RegisterManagerResponse
	(*DeclareManagerResponse)(nil),        // 12: codespace.v1.DeclareManagerResponse
	(*PingResponse)(nil),                  // 13: codespace.v1.PingResponse
	(*FetchTaskResponse)(nil),             // 14: codespace.v1.FetchTaskResponse
	(*AppendLogResponse)(nil),             // 15: codespace.v1.AppendLogResponse
	(*FinishTaskResponse)(nil),            // 16: codespace.v1.FinishTaskResponse
	(*ReportCodespaceStatusResponse)(nil), // 17: codespace.v1.ReportCodespaceStatusResponse
	(*ReportCodespacePortsResponse)(nil),  // 18: codespace.v1.ReportCodespacePortsResponse
	(*RequestGitTokenResponse)(nil),       // 19: codespace.v1.RequestGitTokenResponse
	(*RevokeGitTokenResponse)(nil),        // 20: codespace.v1.RevokeGitTokenResponse
	(*ValidateAccessTicketResponse)(nil),  // 21: codespace.v1.ValidateAccessTicketResponse
}
var file_codespace_v1_service_proto_depIdxs = []int32{
	0,  // 0: codespace.v1.CodespaceService.RegisterManager:input_type -> codespace.v1.RegisterManagerRequest
	1,  // 1: codespace.v1.CodespaceService.DeclareManager:input_type -> codespace.v1.DeclareManagerRequest
	2,  // 2: codespace.v1.CodespaceService.Ping:input_type -> codespace.v1.PingRequest
	3,  // 3: codespace.v1.CodespaceService.FetchTask:input_type -> codespace.v1.FetchTaskRequest
	4,  // 4: codespace.v1.CodespaceService.AppendLog:input_type -> codespace.v1.AppendLogRequest
	5,  // 5: codespace.v1.CodespaceService.FinishTask:input_type -> codespace.v1.FinishTaskRequest
	6,  // 6: codespace.v1.CodespaceService.ReportCodespaceStatus:input_type -> codespace.v1.ReportCodespaceStatusRequest
	7,  // 7: codespace.v1.CodespaceService.ReportCodespacePorts:input_type -> codespace.v1.ReportCodespacePortsRequest
	8,  // 8: codespace.v1.CodespaceService.RequestGitToken:input_type -> codespace.v1.RequestGitTokenRequest
	9,  // 9: codespace.v1.CodespaceService.RevokeGitToken:input_type -> codespace.v1.RevokeGitTokenRequest
	10, // 10: codespace.v1.CodespaceService.ValidateAccessTicket:input_type -> codespace.v1.ValidateAccessTicketRequest
	11, // 11: codespace.v1.CodespaceService.RegisterManager:output_type -> codespace.v1.RegisterManagerResponse
	12, // 12: codespace.v1.CodespaceService.DeclareManager:output_type -> codespace.v1.DeclareManagerResponse
	13, // 13: codespace.v1.CodespaceService.Ping:output_type -> codespace.v1.PingResponse
	14, // 14: codespace.v1.CodespaceService.FetchTask:output_type -> codespace.v1.FetchTaskResponse
	15, // 15: codespace.v1.CodespaceService.AppendLog:output_type -> codespace.v1.AppendLogResponse
	16, // 16: codespace.v1.CodespaceService.FinishTask:output_type -> codespace.v1.FinishTaskResponse
	17, // 17: codespace.v1.CodespaceService.ReportCodespaceStatus:output_type -> codespace.v1.ReportCodespaceStatusResponse
	18, // 18: codespace.v1.CodespaceService.ReportCodespacePorts:output_type -> codespace.v1.ReportCodespacePortsResponse
	19, // 19: codespace.v1.CodespaceService.RequestGitToken:output_type -> codespace.v1.RequestGitTokenResponse
	20, // 20: codespace.v1.CodespaceService.RevokeGitToken:output_type -> codespace.v1.RevokeGitTokenResponse
	21, // 21: codespace.v1.CodespaceService.ValidateAccessTicket:output_type -> codespace.v1.ValidateAccessTicketResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_codespace_v1_service_proto_init() }
func file_codespace_v1_service_proto_init() {
	if File_codespace_v1_service_proto != nil {
		return
	}
	file_codespace_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codespace_v1_service_proto_rawDesc), len(file_codespace_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_codespace_v1_service_proto_goTypes,
		DependencyIndexes: file_codespace_v1_service_proto_depIdxs,
	}.Build()
	File_codespace_v1_service_proto = out.File
	file_codespace_v1_service_proto_goTypes = nil
	file_codespace_v1_service_proto_depIdxs = nil
}
