// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: codespace/v1/types.proto

package codespacev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ManagerStatus describes the liveness state reported by a codespace manager.
type ManagerStatus int32

const (
	// MANAGER_STATUS_UNSPECIFIED should not be emitted by managers.
	ManagerStatus_MANAGER_STATUS_UNSPECIFIED ManagerStatus = 0
	// MANAGER_STATUS_ONLINE means the manager is healthy and can accept work.
	ManagerStatus_MANAGER_STATUS_ONLINE ManagerStatus = 1
	// MANAGER_STATUS_OFFLINE means the manager is not currently reachable.
	ManagerStatus_MANAGER_STATUS_OFFLINE ManagerStatus = 2
	// MANAGER_STATUS_DISABLED means the manager is administratively disabled.
	ManagerStatus_MANAGER_STATUS_DISABLED ManagerStatus = 3
)

// Enum value maps for ManagerStatus.
var (
	ManagerStatus_name = map[int32]string{
		0: "MANAGER_STATUS_UNSPECIFIED",
		1: "MANAGER_STATUS_ONLINE",
		2: "MANAGER_STATUS_OFFLINE",
		3: "MANAGER_STATUS_DISABLED",
	}
	ManagerStatus_value = map[string]int32{
		"MANAGER_STATUS_UNSPECIFIED": 0,
		"MANAGER_STATUS_ONLINE":      1,
		"MANAGER_STATUS_OFFLINE":     2,
		"MANAGER_STATUS_DISABLED":    3,
	}
)

func (x ManagerStatus) Enum() *ManagerStatus {
	p := new(ManagerStatus)
	*p = x
	return p
}

func (x ManagerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ManagerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_codespace_v1_types_proto_enumTypes[0].Descriptor()
}

func (ManagerStatus) Type() protoreflect.EnumType {
	return &file_codespace_v1_types_proto_enumTypes[0]
}

func (x ManagerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ManagerStatus.Descriptor instead.
func (ManagerStatus) EnumDescriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{0}
}

// CodespaceStatus describes the lifecycle state of one codespace instance.
type CodespaceStatus int32

const (
	// CODESPACE_STATUS_UNSPECIFIED should be treated as unknown by receivers.
	CodespaceStatus_CODESPACE_STATUS_UNSPECIFIED CodespaceStatus = 0
	// CODESPACE_STATUS_INITIALIZING means create or resume is in progress.
	CodespaceStatus_CODESPACE_STATUS_INITIALIZING CodespaceStatus = 1
	// CODESPACE_STATUS_RUNNING means the runtime is ready for user access.
	CodespaceStatus_CODESPACE_STATUS_RUNNING CodespaceStatus = 2
	// CODESPACE_STATUS_STOPPED means the runtime is stopped but can be resumed.
	CodespaceStatus_CODESPACE_STATUS_STOPPED CodespaceStatus = 3
	// CODESPACE_STATUS_STOPPING means the runtime is being stopped.
	CodespaceStatus_CODESPACE_STATUS_STOPPING CodespaceStatus = 4
	// CODESPACE_STATUS_DELETING means the runtime is being removed.
	CodespaceStatus_CODESPACE_STATUS_DELETING CodespaceStatus = 5
	// CODESPACE_STATUS_ERROR means the latest lifecycle operation failed.
	CodespaceStatus_CODESPACE_STATUS_ERROR CodespaceStatus = 6
)

// Enum value maps for CodespaceStatus.
var (
	CodespaceStatus_name = map[int32]string{
		0: "CODESPACE_STATUS_UNSPECIFIED",
		1: "CODESPACE_STATUS_INITIALIZING",
		2: "CODESPACE_STATUS_RUNNING",
		3: "CODESPACE_STATUS_STOPPED",
		4: "CODESPACE_STATUS_STOPPING",
		5: "CODESPACE_STATUS_DELETING",
		6: "CODESPACE_STATUS_ERROR",
	}
	CodespaceStatus_value = map[string]int32{
		"CODESPACE_STATUS_UNSPECIFIED":  0,
		"CODESPACE_STATUS_INITIALIZING": 1,
		"CODESPACE_STATUS_RUNNING":      2,
		"CODESPACE_STATUS_STOPPED":      3,
		"CODESPACE_STATUS_STOPPING":     4,
		"CODESPACE_STATUS_DELETING":     5,
		"CODESPACE_STATUS_ERROR":        6,
	}
)

func (x CodespaceStatus) Enum() *CodespaceStatus {
	p := new(CodespaceStatus)
	*p = x
	return p
}

func (x CodespaceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CodespaceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_codespace_v1_types_proto_enumTypes[1].Descriptor()
}

func (CodespaceStatus) Type() protoreflect.EnumType {
	return &file_codespace_v1_types_proto_enumTypes[1]
}

func (x CodespaceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CodespaceStatus.Descriptor instead.
func (CodespaceStatus) EnumDescriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{1}
}

// OperationType describes the operation a manager should perform.
type OperationType int32

const (
	// OPERATION_TYPE_UNSPECIFIED should not be used for queued operations.
	OperationType_OPERATION_TYPE_UNSPECIFIED OperationType = 0
	// OPERATION_TYPE_CREATE creates and bootstraps a new runtime.
	OperationType_OPERATION_TYPE_CREATE OperationType = 1
	// OPERATION_TYPE_RESUME starts an existing stopped runtime.
	OperationType_OPERATION_TYPE_RESUME OperationType = 2
	// OPERATION_TYPE_STOP stops a runtime without deleting persistent state.
	OperationType_OPERATION_TYPE_STOP OperationType = 3
	// OPERATION_TYPE_DELETE permanently removes a runtime.
	OperationType_OPERATION_TYPE_DELETE OperationType = 4
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OPERATION_TYPE_UNSPECIFIED",
		1: "OPERATION_TYPE_CREATE",
		2: "OPERATION_TYPE_RESUME",
		3: "OPERATION_TYPE_STOP",
		4: "OPERATION_TYPE_DELETE",
	}
	OperationType_value = map[string]int32{
		"OPERATION_TYPE_UNSPECIFIED": 0,
		"OPERATION_TYPE_CREATE":      1,
		"OPERATION_TYPE_RESUME":      2,
		"OPERATION_TYPE_STOP":        3,
		"OPERATION_TYPE_DELETE":      4,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_codespace_v1_types_proto_enumTypes[2].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_codespace_v1_types_proto_enumTypes[2]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{2}
}

// OperationStatus describes operation lease and execution state.
type OperationStatus int32

const (
	// OPERATION_STATUS_UNSPECIFIED should not be persisted for operations.
	OperationStatus_OPERATION_STATUS_UNSPECIFIED OperationStatus = 0
	// OPERATION_STATUS_QUEUED means the operation is available for leasing.
	OperationStatus_OPERATION_STATUS_QUEUED OperationStatus = 1
	// OPERATION_STATUS_LEASED means a manager has reserved the operation.
	OperationStatus_OPERATION_STATUS_LEASED OperationStatus = 2
	// OPERATION_STATUS_RUNNING means the manager is actively executing the operation.
	OperationStatus_OPERATION_STATUS_RUNNING OperationStatus = 3
	// OPERATION_STATUS_SUCCEEDED means the operation finished successfully.
	OperationStatus_OPERATION_STATUS_SUCCEEDED OperationStatus = 4
	// OPERATION_STATUS_FAILED means the operation finished with an error.
	OperationStatus_OPERATION_STATUS_FAILED OperationStatus = 5
	// OPERATION_STATUS_CANCELLED means the operation was intentionally abandoned.
	OperationStatus_OPERATION_STATUS_CANCELLED OperationStatus = 6
)

// Enum value maps for OperationStatus.
var (
	OperationStatus_name = map[int32]string{
		0: "OPERATION_STATUS_UNSPECIFIED",
		1: "OPERATION_STATUS_QUEUED",
		2: "OPERATION_STATUS_LEASED",
		3: "OPERATION_STATUS_RUNNING",
		4: "OPERATION_STATUS_SUCCEEDED",
		5: "OPERATION_STATUS_FAILED",
		6: "OPERATION_STATUS_CANCELLED",
	}
	OperationStatus_value = map[string]int32{
		"OPERATION_STATUS_UNSPECIFIED": 0,
		"OPERATION_STATUS_QUEUED":      1,
		"OPERATION_STATUS_LEASED":      2,
		"OPERATION_STATUS_RUNNING":     3,
		"OPERATION_STATUS_SUCCEEDED":   4,
		"OPERATION_STATUS_FAILED":      5,
		"OPERATION_STATUS_CANCELLED":   6,
	}
)

func (x OperationStatus) Enum() *OperationStatus {
	p := new(OperationStatus)
	*p = x
	return p
}

func (x OperationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_codespace_v1_types_proto_enumTypes[3].Descriptor()
}

func (OperationStatus) Type() protoreflect.EnumType {
	return &file_codespace_v1_types_proto_enumTypes[3]
}

func (x OperationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationStatus.Descriptor instead.
func (OperationStatus) EnumDescriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{3}
}

// PortVisibility controls who can access a forwarded codespace port.
type PortVisibility int32

const (
	// PORT_VISIBILITY_UNSPECIFIED defaults to private.
	PortVisibility_PORT_VISIBILITY_UNSPECIFIED PortVisibility = 0
	// PORT_VISIBILITY_PRIVATE restricts access to the codespace owner.
	PortVisibility_PORT_VISIBILITY_PRIVATE PortVisibility = 1
	// PORT_VISIBILITY_ORG restricts access to organization members.
	PortVisibility_PORT_VISIBILITY_ORG PortVisibility = 2
	// PORT_VISIBILITY_PUBLIC allows unauthenticated public access when enabled.
	PortVisibility_PORT_VISIBILITY_PUBLIC PortVisibility = 3
)

// Enum value maps for PortVisibility.
var (
	PortVisibility_name = map[int32]string{
		0: "PORT_VISIBILITY_UNSPECIFIED",
		1: "PORT_VISIBILITY_PRIVATE",
		2: "PORT_VISIBILITY_ORG",
		3: "PORT_VISIBILITY_PUBLIC",
	}
	PortVisibility_value = map[string]int32{
		"PORT_VISIBILITY_UNSPECIFIED": 0,
		"PORT_VISIBILITY_PRIVATE":     1,
		"PORT_VISIBILITY_ORG":         2,
		"PORT_VISIBILITY_PUBLIC":      3,
	}
)

func (x PortVisibility) Enum() *PortVisibility {
	p := new(PortVisibility)
	*p = x
	return p
}

func (x PortVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PortVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_codespace_v1_types_proto_enumTypes[4].Descriptor()
}

func (PortVisibility) Type() protoreflect.EnumType {
	return &file_codespace_v1_types_proto_enumTypes[4]
}

func (x PortVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PortVisibility.Descriptor instead.
func (PortVisibility) EnumDescriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{4}
}

// PortStatus describes the manager-reported state of a forwarded port.
type PortStatus int32

const (
	// PORT_STATUS_UNSPECIFIED should be treated as inactive.
	PortStatus_PORT_STATUS_UNSPECIFIED PortStatus = 0
	// PORT_STATUS_ACTIVE means the port is currently reachable.
	PortStatus_PORT_STATUS_ACTIVE PortStatus = 1
	// PORT_STATUS_INACTIVE means the port is declared but not reachable.
	PortStatus_PORT_STATUS_INACTIVE PortStatus = 2
	// PORT_STATUS_ERROR means the manager failed to expose the port.
	PortStatus_PORT_STATUS_ERROR PortStatus = 3
	// PORT_STATUS_DELETED means the declaration should no longer be shown.
	PortStatus_PORT_STATUS_DELETED PortStatus = 4
)

// Enum value maps for PortStatus.
var (
	PortStatus_name = map[int32]string{
		0: "PORT_STATUS_UNSPECIFIED",
		1: "PORT_STATUS_ACTIVE",
		2: "PORT_STATUS_INACTIVE",
		3: "PORT_STATUS_ERROR",
		4: "PORT_STATUS_DELETED",
	}
	PortStatus_value = map[string]int32{
		"PORT_STATUS_UNSPECIFIED": 0,
		"PORT_STATUS_ACTIVE":      1,
		"PORT_STATUS_INACTIVE":    2,
		"PORT_STATUS_ERROR":       3,
		"PORT_STATUS_DELETED":     4,
	}
)

func (x PortStatus) Enum() *PortStatus {
	p := new(PortStatus)
	*p = x
	return p
}

func (x PortStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PortStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_codespace_v1_types_proto_enumTypes[5].Descriptor()
}

func (PortStatus) Type() protoreflect.EnumType {
	return &file_codespace_v1_types_proto_enumTypes[5]
}

func (x PortStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PortStatus.Descriptor instead.
func (PortStatus) EnumDescriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{5}
}

// ManagerFeatures lists optional gateway capabilities supported by a manager.
type ManagerFeatures struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// web indicates browser access to codespace runtimes is supported.
	Web bool `protobuf:"varint,1,opt,name=web,proto3" json:"web,omitempty"`
	// ssh indicates SSH access is supported.
	Ssh bool `protobuf:"varint,2,opt,name=ssh,proto3" json:"ssh,omitempty"`
	// port_preview indicates forwarded port previews are supported.
	PortPreview bool `protobuf:"varint,3,opt,name=port_preview,json=portPreview,proto3" json:"port_preview,omitempty"`
	// public_port indicates the manager can expose unauthenticated public ports.
	PublicPort    bool `protobuf:"varint,4,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerFeatures) Reset() {
	*x = ManagerFeatures{}
	mi := &file_codespace_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerFeatures) ProtoMessage() {}

func (x *ManagerFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerFeatures.ProtoReflect.Descriptor instead.
func (*ManagerFeatures) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *ManagerFeatures) GetWeb() bool {
	if x != nil {
		return x.Web
	}
	return false
}

func (x *ManagerFeatures) GetSsh() bool {
	if x != nil {
		return x.Ssh
	}
	return false
}

func (x *ManagerFeatures) GetPortPreview() bool {
	if x != nil {
		return x.PortPreview
	}
	return false
}

func (x *ManagerFeatures) GetPublicPort() bool {
	if x != nil {
		return x.PublicPort
	}
	return false
}

// ResourcePreset describes one named compute shape offered by a manager.
type ResourcePreset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the stable preset identifier selected by users.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// cpu is a manager-defined CPU quantity such as "2".
	Cpu string `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	// memory is a manager-defined memory quantity such as "4GiB".
	Memory string `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`
	// disk is a manager-defined disk quantity such as "40GiB".
	Disk          string `protobuf:"bytes,4,opt,name=disk,proto3" json:"disk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcePreset) Reset() {
	*x = ResourcePreset{}
	mi := &file_codespace_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcePreset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcePreset) ProtoMessage() {}

func (x *ResourcePreset) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcePreset.ProtoReflect.Descriptor instead.
func (*ResourcePreset) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *ResourcePreset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourcePreset) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *ResourcePreset) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *ResourcePreset) GetDisk() string {
	if x != nil {
		return x.Disk
	}
	return ""
}

// ManagerCapabilities is the manager-declared runtime catalog consumed by
// Gitea UI and task creation.
type ManagerCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// gateway_url is the externally reachable base URL for user access.
	GatewayUrl string `protobuf:"bytes,1,opt,name=gateway_url,json=gatewayUrl,proto3" json:"gateway_url,omitempty"`
	// version is the manager software version.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// labels are manager-defined selectors and descriptive tags.
	Labels []string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	// max_concurrency is the maximum number of concurrent codespace workloads.
	MaxConcurrency int32 `protobuf:"varint,4,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`
	// current_concurrency is the current number of active workloads.
	CurrentConcurrency int32 `protobuf:"varint,5,opt,name=current_concurrency,json=currentConcurrency,proto3" json:"current_concurrency,omitempty"`
	// supported_instance_types contains values such as "container" or "vm".
	SupportedInstanceTypes []string `protobuf:"bytes,6,rep,name=supported_instance_types,json=supportedInstanceTypes,proto3" json:"supported_instance_types,omitempty"`
	// images contains manager-supported image identifiers.
	Images []string `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"`
	// resource_presets contains named compute shapes.
	ResourcePresets []*ResourcePreset `protobuf:"bytes,8,rep,name=resource_presets,json=resourcePresets,proto3" json:"resource_presets,omitempty"`
	// features lists optional gateway capabilities.
	Features *ManagerFeatures `protobuf:"bytes,9,opt,name=features,proto3" json:"features,omitempty"`
	// default_init_script is used when a codespace is created without override.
	DefaultInitScript string `protobuf:"bytes,10,opt,name=default_init_script,json=defaultInitScript,proto3" json:"default_init_script,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ManagerCapabilities) Reset() {
	*x = ManagerCapabilities{}
	mi := &file_codespace_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerCapabilities) ProtoMessage() {}

func (x *ManagerCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerCapabilities.ProtoReflect.Descriptor instead.
func (*ManagerCapabilities) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *ManagerCapabilities) GetGatewayUrl() string {
	if x != nil {
		return x.GatewayUrl
	}
	return ""
}

func (x *ManagerCapabilities) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ManagerCapabilities) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ManagerCapabilities) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

func (x *ManagerCapabilities) GetCurrentConcurrency() int32 {
	if x != nil {
		return x.CurrentConcurrency
	}
	return 0
}

func (x *ManagerCapabilities) GetSupportedInstanceTypes() []string {
	if x != nil {
		return x.SupportedInstanceTypes
	}
	return nil
}

func (x *ManagerCapabilities) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ManagerCapabilities) GetResourcePresets() []*ResourcePreset {
	if x != nil {
		return x.ResourcePresets
	}
	return nil
}

func (x *ManagerCapabilities) GetFeatures() *ManagerFeatures {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *ManagerCapabilities) GetDefaultInitScript() string {
	if x != nil {
		return x.DefaultInitScript
	}
	return ""
}

// RegisterManagerRequest registers a manager with a scope-bound registration
// token. This request is not authenticated with manager headers.
type RegisterManagerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// registration_token is the active token copied from the Gitea UI.
	RegistrationToken string `protobuf:"bytes,1,opt,name=registration_token,json=registrationToken,proto3" json:"registration_token,omitempty"`
	// name is the human-readable manager name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// gateway_url is the externally reachable manager gateway URL.
	GatewayUrl string `protobuf:"bytes,3,opt,name=gateway_url,json=gatewayUrl,proto3" json:"gateway_url,omitempty"`
	// version is the manager software version.
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// capabilities is the initial runtime catalog for this manager.
	Capabilities  *ManagerCapabilities `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterManagerRequest) Reset() {
	*x = RegisterManagerRequest{}
	mi := &file_codespace_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterManagerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterManagerRequest) ProtoMessage() {}

func (x *RegisterManagerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterManagerRequest.ProtoReflect.Descriptor instead.
func (*RegisterManagerRequest) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterManagerRequest) GetRegistrationToken() string {
	if x != nil {
		return x.RegistrationToken
	}
	return ""
}

func (x *RegisterManagerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterManagerRequest) GetGatewayUrl() string {
	if x != nil {
		return x.GatewayUrl
	}
	return ""
}

func (x *RegisterManagerRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterManagerRequest) GetCapabilities() *ManagerCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// RegisterManagerResponse contains the manager identity and one-time clear
// manager token. The token must be stored by the manager; Gitea stores only a
// salted hash.
type RegisterManagerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// manager_id is the Gitea database ID.
	ManagerId int64 `protobuf:"varint,1,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	// manager_uuid is the stable public manager identifier.
	ManagerUuid string `protobuf:"bytes,2,opt,name=manager_uuid,json=managerUuid,proto3" json:"manager_uuid,omitempty"`
	// manager_token is the one-time clear token used in manager auth headers.
	ManagerToken  string `protobuf:"bytes,3,opt,name=manager_token,json=managerToken,proto3" json:"manager_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterManagerResponse) Reset() {
	*x = RegisterManagerResponse{}
	mi := &file_codespace_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterManagerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterManagerResponse) ProtoMessage() {}

func (x *RegisterManagerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterManagerResponse.ProtoReflect.Descriptor instead.
func (*RegisterManagerResponse) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterManagerResponse) GetManagerId() int64 {
	if x != nil {
		return x.ManagerId
	}
	return 0
}

func (x *RegisterManagerResponse) GetManagerUuid() string {
	if x != nil {
		return x.ManagerUuid
	}
	return ""
}

func (x *RegisterManagerResponse) GetManagerToken() string {
	if x != nil {
		return x.ManagerToken
	}
	return ""
}

// DeclareManagerRequest refreshes metadata and capabilities for the
// authenticated manager. The manager identity comes from request headers.
type DeclareManagerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the human-readable manager name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// gateway_url is the externally reachable manager gateway URL.
	GatewayUrl string `protobuf:"bytes,2,opt,name=gateway_url,json=gatewayUrl,proto3" json:"gateway_url,omitempty"`
	// version is the manager software version.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// capabilities is the latest runtime catalog for this manager.
	Capabilities  *ManagerCapabilities `protobuf:"bytes,4,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclareManagerRequest) Reset() {
	*x = DeclareManagerRequest{}
	mi := &file_codespace_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclareManagerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclareManagerRequest) ProtoMessage() {}

func (x *DeclareManagerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclareManagerRequest.ProtoReflect.Descriptor instead.
func (*DeclareManagerRequest) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *DeclareManagerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeclareManagerRequest) GetGatewayUrl() string {
	if x != nil {
		return x.GatewayUrl
	}
	return ""
}

func (x *DeclareManagerRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DeclareManagerRequest) GetCapabilities() *ManagerCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// DeclareManagerResponse acknowledges a manager declaration.
type DeclareManagerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// accepted is true when the declaration was stored.
	Accepted      bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclareManagerResponse) Reset() {
	*x = DeclareManagerResponse{}
	mi := &file_codespace_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclareManagerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclareManagerResponse) ProtoMessage() {}

func (x *DeclareManagerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclareManagerResponse.ProtoReflect.Descriptor instead.
func (*DeclareManagerResponse) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *DeclareManagerResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

// PingRequest reports liveness and load for the authenticated manager.
type PingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is the manager-reported liveness state.
	Status ManagerStatus `protobuf:"varint,1,opt,name=status,proto3,enum=codespace.v1.ManagerStatus" json:"status,omitempty"`
	// current_concurrency is the current number of active workloads.
	CurrentConcurrency int32 `protobuf:"varint,2,opt,name=current_concurrency,json=currentConcurrency,proto3" json:"current_concurrency,omitempty"`
	// load is a manager-defined normalized load value.
	Load          float64 `protobuf:"fixed64,3,opt,name=load,proto3" json:"load,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_codespace_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *PingRequest) GetStatus() ManagerStatus {
	if x != nil {
		return x.Status
	}
	return ManagerStatus_MANAGER_STATUS_UNSPECIFIED
}

func (x *PingRequest) GetCurrentConcurrency() int32 {
	if x != nil {
		return x.CurrentConcurrency
	}
	return 0
}

func (x *PingRequest) GetLoad() float64 {
	if x != nil {
		return x.Load
	}
	return 0
}

// PingResponse returns server timing information.
type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server_time is the Gitea server Unix timestamp in seconds.
	ServerTime    int64 `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_codespace_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *PingResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// CodespaceOperationPayload contains the runtime inputs needed by a manager.
type CodespaceOperationPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// instance_name is the manager-side runtime instance name.
	InstanceName string `protobuf:"bytes,1,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	// instance_type is the selected runtime type.
	InstanceType string `protobuf:"bytes,2,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	// image is the selected runtime image.
	Image string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	// resource_preset is the selected compute preset.
	ResourcePreset string `protobuf:"bytes,4,opt,name=resource_preset,json=resourcePreset,proto3" json:"resource_preset,omitempty"`
	// repo_url is the clone URL used by the runtime.
	RepoUrl string `protobuf:"bytes,5,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	// repo_full_name is the repository full name in owner/name form.
	RepoFullName string `protobuf:"bytes,6,opt,name=repo_full_name,json=repoFullName,proto3" json:"repo_full_name,omitempty"`
	// start_ref is the resolved Git ref to fetch, such as refs/heads/main or refs/pull/1/head.
	StartRef string `protobuf:"bytes,7,opt,name=start_ref,json=startRef,proto3" json:"start_ref,omitempty"`
	// start_sha is the exact commit to check out after fetching start_ref.
	StartSha string `protobuf:"bytes,8,opt,name=start_sha,json=startSha,proto3" json:"start_sha,omitempty"`
	// init_script is executed by the manager during bootstrap.
	InitScript    string `protobuf:"bytes,9,opt,name=init_script,json=initScript,proto3" json:"init_script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodespaceOperationPayload) Reset() {
	*x = CodespaceOperationPayload{}
	mi := &file_codespace_v1_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodespaceOperationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodespaceOperationPayload) ProtoMessage() {}

func (x *CodespaceOperationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodespaceOperationPayload.ProtoReflect.Descriptor instead.
func (*CodespaceOperationPayload) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *CodespaceOperationPayload) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *CodespaceOperationPayload) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *CodespaceOperationPayload) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CodespaceOperationPayload) GetResourcePreset() string {
	if x != nil {
		return x.ResourcePreset
	}
	return ""
}

func (x *CodespaceOperationPayload) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *CodespaceOperationPayload) GetRepoFullName() string {
	if x != nil {
		return x.RepoFullName
	}
	return ""
}

func (x *CodespaceOperationPayload) GetStartRef() string {
	if x != nil {
		return x.StartRef
	}
	return ""
}

func (x *CodespaceOperationPayload) GetStartSha() string {
	if x != nil {
		return x.StartSha
	}
	return ""
}

func (x *CodespaceOperationPayload) GetInitScript() string {
	if x != nil {
		return x.InitScript
	}
	return ""
}

// CodespaceOperation is one leased unit of work returned to a manager.
type CodespaceOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// task_id is the stable task UUID used for lease tracking.
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// codespace_id is the stable codespace UUID.
	CodespaceId string `protobuf:"bytes,2,opt,name=codespace_id,json=codespaceId,proto3" json:"codespace_id,omitempty"`
	// type is the operation to execute.
	Type OperationType `protobuf:"varint,3,opt,name=type,proto3,enum=codespace.v1.OperationType" json:"type,omitempty"`
	// payload contains runtime inputs for the operation.
	Payload *CodespaceOperationPayload `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// lease_deadline is the Unix timestamp in seconds when the lease expires.
	LeaseDeadline int64 `protobuf:"varint,5,opt,name=lease_deadline,json=leaseDeadline,proto3" json:"lease_deadline,omitempty"`
	// operation_id is the active operation UUID. All follow-up reports must echo it.
	OperationId   string `protobuf:"bytes,6,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodespaceOperation) Reset() {
	*x = CodespaceOperation{}
	mi := &file_codespace_v1_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodespaceOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodespaceOperation) ProtoMessage() {}

func (x *CodespaceOperation) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodespaceOperation.ProtoReflect.Descriptor instead.
func (*CodespaceOperation) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{10}
}

func (x *CodespaceOperation) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CodespaceOperation) GetCodespaceId() string {
	if x != nil {
		return x.CodespaceId
	}
	return ""
}

func (x *CodespaceOperation) GetType() OperationType {
	if x != nil {
		return x.Type
	}
	return OperationType_OPERATION_TYPE_UNSPECIFIED
}

func (x *CodespaceOperation) GetPayload() *CodespaceOperationPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CodespaceOperation) GetLeaseDeadline() int64 {
	if x != nil {
		return x.LeaseDeadline
	}
	return 0
}

func (x *CodespaceOperation) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

// FetchTaskRequest asks for work for the authenticated manager.
type FetchTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// capacity is the maximum number of tasks to lease. Values <= 0 mean one.
	Capacity      int32 `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchTaskRequest) Reset() {
	*x = FetchTaskRequest{}
	mi := &file_codespace_v1_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchTaskRequest) ProtoMessage() {}

func (x *FetchTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchTaskRequest.ProtoReflect.Descriptor instead.
func (*FetchTaskRequest) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{11}
}

func (x *FetchTaskRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

// FetchTaskResponse contains tasks leased to the authenticated manager.
type FetchTaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tasks is the ordered list of leased operations.
	Tasks         []*CodespaceOperation `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchTaskResponse) Reset() {
	*x = FetchTaskResponse{}
	mi := &file_codespace_v1_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchTaskResponse) ProtoMessage() {}

func (x *FetchTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchTaskResponse.ProtoReflect.Descriptor instead.
func (*FetchTaskResponse) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{12}
}

func (x *FetchTaskResponse) GetTasks() []*CodespaceOperation {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// TaskResult contains manager-produced runtime outputs.
type TaskResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// instance_name is the final manager-side runtime instance name.
	InstanceName string `protobuf:"bytes,1,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	// workdir is the codespace directory inside the runtime.
	Workdir       string `protobuf:"bytes,2,opt,name=workdir,proto3" json:"workdir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_codespace_v1_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{13}
}

func (x *TaskResult) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *TaskResult) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

// FinishTaskRequest records the authenticated manager's result for a task.
type FinishTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// task_id is the stable task UUID.
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// status is the final task state.
	Status OperationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=codespace.v1.OperationStatus" json:"status,omitempty"`
	// result contains runtime outputs when the task succeeds or partially ran.
	Result *TaskResult `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	// error is a human-readable failure message.
	Error string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// operation_id is the active operation UUID.
	OperationId   string `protobuf:"bytes,5,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishTaskRequest) Reset() {
	*x = FinishTaskRequest{}
	mi := &file_codespace_v1_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTaskRequest) ProtoMessage() {}

func (x *FinishTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTaskRequest.ProtoReflect.Descriptor instead.
func (*FinishTaskRequest) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{14}
}

func (x *FinishTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *FinishTaskRequest) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *FinishTaskRequest) GetResult() *TaskResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *FinishTaskRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FinishTaskRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

// FinishTaskResponse is empty on success.
type FinishTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishTaskResponse) Reset() {
	*x = FinishTaskResponse{}
	mi := &file_codespace_v1_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTaskResponse) ProtoMessage() {}

func (x *FinishTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTaskResponse.ProtoReflect.Descriptor instead.
func (*FinishTaskResponse) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{15}
}

// ReportCodespaceStatusRequest updates a codespace state snapshot.
type ReportCodespaceStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// codespace_id is the stable codespace UUID.
	CodespaceId string `protobuf:"bytes,1,opt,name=codespace_id,json=codespaceId,proto3" json:"codespace_id,omitempty"`
	// status is the current runtime lifecycle state.
	Status CodespaceStatus `protobuf:"varint,2,opt,name=status,proto3,enum=codespace.v1.CodespaceStatus" json:"status,omitempty"`
	// last_active_unix is a Unix timestamp in seconds, or zero if unchanged.
	LastActiveUnix int64 `protobuf:"varint,3,opt,name=last_active_unix,json=lastActiveUnix,proto3" json:"last_active_unix,omitempty"`
	// error is a human-readable runtime error message.
	Error string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// operation_id is the active operation UUID.
	OperationId   string `protobuf:"bytes,5,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCodespaceStatusRequest) Reset() {
	*x = ReportCodespaceStatusRequest{}
	mi := &file_codespace_v1_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCodespaceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCodespaceStatusRequest) ProtoMessage() {}

func (x *ReportCodespaceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCodespaceStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportCodespaceStatusRequest) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{16}
}

func (x *ReportCodespaceStatusRequest) GetCodespaceId() string {
	if x != nil {
		return x.CodespaceId
	}
	return ""
}

func (x *ReportCodespaceStatusRequest) GetStatus() CodespaceStatus {
	if x != nil {
		return x.Status
	}
	return CodespaceStatus_CODESPACE_STATUS_UNSPECIFIED
}

func (x *ReportCodespaceStatusRequest) GetLastActiveUnix() int64 {
	if x != nil {
		return x.LastActiveUnix
	}
	return 0
}

func (x *ReportCodespaceStatusRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReportCodespaceStatusRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

// ReportCodespaceStatusResponse is empty on success.
type ReportCodespaceStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCodespaceStatusResponse) Reset() {
	*x = ReportCodespaceStatusResponse{}
	mi := &file_codespace_v1_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCodespaceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCodespaceStatusResponse) ProtoMessage() {}

func (x *ReportCodespaceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCodespaceStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportCodespaceStatusResponse) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{17}
}

// CodespacePort describes one runtime port declaration.
type CodespacePort struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is a stable display name unique within the codespace.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// port is the runtime TCP/UDP port number.
	Port int32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// protocol is the application protocol, such as http or tcp.
	Protocol string `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// visibility controls who can access the port.
	Visibility PortVisibility `protobuf:"varint,4,opt,name=visibility,proto3,enum=codespace.v1.PortVisibility" json:"visibility,omitempty"`
	// description is optional user-facing text.
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// public_url is the manager-generated URL when externally exposed.
	PublicUrl string `protobuf:"bytes,6,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	// status is the current port state.
	Status        PortStatus `protobuf:"varint,7,opt,name=status,proto3,enum=codespace.v1.PortStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodespacePort) Reset() {
	*x = CodespacePort{}
	mi := &file_codespace_v1_types_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodespacePort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodespacePort) ProtoMessage() {}

func (x *CodespacePort) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodespacePort.ProtoReflect.Descriptor instead.
func (*CodespacePort) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{18}
}

func (x *CodespacePort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CodespacePort) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CodespacePort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *CodespacePort) GetVisibility() PortVisibility {
	if x != nil {
		return x.Visibility
	}
	return PortVisibility_PORT_VISIBILITY_UNSPECIFIED
}

func (x *CodespacePort) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CodespacePort) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *CodespacePort) GetStatus() PortStatus {
	if x != nil {
		return x.Status
	}
	return PortStatus_PORT_STATUS_UNSPECIFIED
}

// ReportCodespacePortsRequest replaces the full visible port set for a
// codespace.
type ReportCodespacePortsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// codespace_id is the stable codespace UUID.
	CodespaceId string `protobuf:"bytes,1,opt,name=codespace_id,json=codespaceId,proto3" json:"codespace_id,omitempty"`
	// ports is the complete desired visible port set.
	Ports []*CodespacePort `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	// operation_id is the active operation UUID.
	OperationId   string `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCodespacePortsRequest) Reset() {
	*x = ReportCodespacePortsRequest{}
	mi := &file_codespace_v1_types_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCodespacePortsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCodespacePortsRequest) ProtoMessage() {}

func (x *ReportCodespacePortsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCodespacePortsRequest.ProtoReflect.Descriptor instead.
func (*ReportCodespacePortsRequest) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{19}
}

func (x *ReportCodespacePortsRequest) GetCodespaceId() string {
	if x != nil {
		return x.CodespaceId
	}
	return ""
}

func (x *ReportCodespacePortsRequest) GetPorts() []*CodespacePort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ReportCodespacePortsRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

// ReportCodespacePortsResponse is empty on success.
type ReportCodespacePortsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCodespacePortsResponse) Reset() {
	*x = ReportCodespacePortsResponse{}
	mi := &file_codespace_v1_types_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCodespacePortsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCodespacePortsResponse) ProtoMessage() {}

func (x *ReportCodespacePortsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCodespacePortsResponse.ProtoReflect.Descriptor instead.
func (*ReportCodespacePortsResponse) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{20}
}

// RequestGitTokenRequest asks Gitea to issue a short-lived repository token for
// a codespace owned by the authenticated manager.
type RequestGitTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// codespace_id is the stable codespace UUID.
	CodespaceId string `protobuf:"bytes,1,opt,name=codespace_id,json=codespaceId,proto3" json:"codespace_id,omitempty"`
	// operation_id is the active operation UUID.
	OperationId   string `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGitTokenRequest) Reset() {
	*x = RequestGitTokenRequest{}
	mi := &file_codespace_v1_types_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGitTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGitTokenRequest) ProtoMessage() {}

func (x *RequestGitTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGitTokenRequest.ProtoReflect.Descriptor instead.
func (*RequestGitTokenRequest) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{21}
}

func (x *RequestGitTokenRequest) GetCodespaceId() string {
	if x != nil {
		return x.CodespaceId
	}
	return ""
}

func (x *RequestGitTokenRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

// RequestGitTokenResponse returns a one-time clear git token for runtime
// bootstrap.
type RequestGitTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username is the credential username to configure in git.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// token is the clear repository token.
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// expires_at is the Unix timestamp in seconds when the token expires.
	ExpiresAt     int64 `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGitTokenResponse) Reset() {
	*x = RequestGitTokenResponse{}
	mi := &file_codespace_v1_types_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGitTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGitTokenResponse) ProtoMessage() {}

func (x *RequestGitTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGitTokenResponse.ProtoReflect.Descriptor instead.
func (*RequestGitTokenResponse) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{22}
}

func (x *RequestGitTokenResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RequestGitTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RequestGitTokenResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// RevokeGitTokenRequest revokes active repository tokens for a codespace.
type RevokeGitTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// codespace_id is the stable codespace UUID.
	CodespaceId string `protobuf:"bytes,1,opt,name=codespace_id,json=codespaceId,proto3" json:"codespace_id,omitempty"`
	// reason is an optional audit/debug reason.
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// operation_id is the active operation UUID.
	OperationId   string `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeGitTokenRequest) Reset() {
	*x = RevokeGitTokenRequest{}
	mi := &file_codespace_v1_types_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeGitTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeGitTokenRequest) ProtoMessage() {}

func (x *RevokeGitTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeGitTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeGitTokenRequest) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{23}
}

func (x *RevokeGitTokenRequest) GetCodespaceId() string {
	if x != nil {
		return x.CodespaceId
	}
	return ""
}

func (x *RevokeGitTokenRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RevokeGitTokenRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

// RevokeGitTokenResponse is empty on success.
type RevokeGitTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeGitTokenResponse) Reset() {
	*x = RevokeGitTokenResponse{}
	mi := &file_codespace_v1_types_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeGitTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeGitTokenResponse) ProtoMessage() {}

func (x *RevokeGitTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeGitTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeGitTokenResponse) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{24}
}

// ValidateAccessTicketRequest validates a user access ticket presented to a
// gateway.
type ValidateAccessTicketRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ticket is the short-lived opaque token generated by Gitea.
	Ticket string `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	// action is the requested gateway action, such as open.
	Action        string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccessTicketRequest) Reset() {
	*x = ValidateAccessTicketRequest{}
	mi := &file_codespace_v1_types_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccessTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccessTicketRequest) ProtoMessage() {}

func (x *ValidateAccessTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccessTicketRequest.ProtoReflect.Descriptor instead.
func (*ValidateAccessTicketRequest) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{25}
}

func (x *ValidateAccessTicketRequest) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *ValidateAccessTicketRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// ValidateAccessTicketResponse contains the ticket validation result and bound
// identity.
type ValidateAccessTicketResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// valid is false when the ticket is missing, expired, consumed, or mismatched.
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// user_id is the Gitea user ID bound to the ticket.
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// codespace_id is the stable codespace UUID bound to the ticket.
	CodespaceId string `protobuf:"bytes,3,opt,name=codespace_id,json=codespaceId,proto3" json:"codespace_id,omitempty"`
	// repo_id is the Gitea repository ID bound to the ticket.
	RepoId int64 `protobuf:"varint,4,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	// action is the validated gateway action.
	Action string `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	// expires_at is the Unix timestamp in seconds when the ticket expires.
	ExpiresAt     int64 `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccessTicketResponse) Reset() {
	*x = ValidateAccessTicketResponse{}
	mi := &file_codespace_v1_types_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccessTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccessTicketResponse) ProtoMessage() {}

func (x *ValidateAccessTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccessTicketResponse.ProtoReflect.Descriptor instead.
func (*ValidateAccessTicketResponse) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{26}
}

func (x *ValidateAccessTicketResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateAccessTicketResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ValidateAccessTicketResponse) GetCodespaceId() string {
	if x != nil {
		return x.CodespaceId
	}
	return ""
}

func (x *ValidateAccessTicketResponse) GetRepoId() int64 {
	if x != nil {
		return x.RepoId
	}
	return 0
}

func (x *ValidateAccessTicketResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ValidateAccessTicketResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// AppendLogRequest appends manager output to the active operation log.
type AppendLogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// codespace_id is the stable codespace UUID.
	CodespaceId string `protobuf:"bytes,1,opt,name=codespace_id,json=codespaceId,proto3" json:"codespace_id,omitempty"`
	// operation_id is the active operation UUID.
	OperationId string `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// task_id is the leased task UUID.
	TaskId string `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// level is a textual log level such as info, warn, or error.
	Level string `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	// message is one log line or chunk.
	Message       string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendLogRequest) Reset() {
	*x = AppendLogRequest{}
	mi := &file_codespace_v1_types_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendLogRequest) ProtoMessage() {}

func (x *AppendLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendLogRequest.ProtoReflect.Descriptor instead.
func (*AppendLogRequest) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{27}
}

func (x *AppendLogRequest) GetCodespaceId() string {
	if x != nil {
		return x.CodespaceId
	}
	return ""
}

func (x *AppendLogRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *AppendLogRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AppendLogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *AppendLogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// AppendLogResponse returns the stored sequence for ordering.
type AppendLogResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sequence is the monotonically increasing operation-local log sequence.
	Sequence      int64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendLogResponse) Reset() {
	*x = AppendLogResponse{}
	mi := &file_codespace_v1_types_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendLogResponse) ProtoMessage() {}

func (x *AppendLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codespace_v1_types_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendLogResponse.ProtoReflect.Descriptor instead.
func (*AppendLogResponse) Descriptor() ([]byte, []int) {
	return file_codespace_v1_types_proto_rawDescGZIP(), []int{28}
}

func (x *AppendLogResponse) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_codespace_v1_types_proto protoreflect.FileDescriptor

const file_codespace_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x18codespace/v1/types.proto\x12\fcodespace.v1\"y\n" +
	"\x0fManagerFeatures\x12\x10\n" +
	"\x03web\x18\x01 \x01(\bR\x03web\x12\x10\n" +
	"\x03ssh\x18\x02 \x01(\bR\x03ssh\x12!\n" +
	"\fport_preview\x18\x03 \x01(\bR\vportPreview\x12\x1f\n" +
	"\vpublic_port\x18\x04 \x01(\bR\n" +
	"publicPort\"b\n" +
	"\x0eResourcePreset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03cpu\x18\x02 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x03 \x01(\tR\x06memory\x12\x12\n" +
	"\x04disk\x18\x04 \x01(\tR\x04disk\"\xc8\x03\n" +
	"\x13ManagerCapabilities\x12\x1f\n" +
	"\vgateway_url\x18\x01 \x01(\tR\n" +
	"gatewayUrl\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06labels\x18\x03 \x03(\tR\x06labels\x12'\n" +
	"\x0fmax_concurrency\x18\x04 \x01(\x05R\x0emaxConcurrency\x12/\n" +
	"\x13current_concurrency\x18\x05 \x01(\x05R\x12currentConcurrency\x128\n" +
	"\x18supported_instance_types\x18\x06 \x03(\tR\x16supportedInstanceTypes\x12\x16\n" +
	"\x06images\x18\a \x03(\tR\x06images\x12G\n" +
	"\x10resource_presets\x18\b \x03(\v2\x1c.codespace.v1.ResourcePresetR\x0fresourcePresets\x129\n" +
	"\bfeatures\x18\t \x01(\v2\x1d.codespace.v1.ManagerFeaturesR\bfeatures\x12.\n" +
	"\x13default_init_script\x18\n" +
	" \x01(\tR\x11defaultInitScript\"\xdd\x01\n" +
	"\x16RegisterManagerRequest\x12-\n" +
	"\x12registration_token\x18\x01 \x01(\tR\x11registrationToken\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vgateway_url\x18\x03 \x01(\tR\n" +
	"gatewayUrl\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12E\n" +
	"\fcapabilities\x18\x05 \x01(\v2!.codespace.v1.ManagerCapabilitiesR\fcapabilities\"\x80\x01\n" +
	"\x17RegisterManagerResponse\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x01 \x01(\x03R\tmanagerId\x12!\n" +
	"\fmanager_uuid\x18\x02 \x01(\tR\vmanagerUuid\x12#\n" +
	"\rmanager_token\x18\x03 \x01(\tR\fmanagerToken\"\xad\x01\n" +
	"\x15DeclareManagerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vgateway_url\x18\x02 \x01(\tR\n" +
	"gatewayUrl\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12E\n" +
	"\fcapabilities\x18\x04 \x01(\v2!.codespace.v1.ManagerCapabilitiesR\fcapabilities\"4\n" +
	"\x16DeclareManagerResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\x87\x01\n" +
	"\vPingRequest\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.codespace.v1.ManagerStatusR\x06status\x12/\n" +
	"\x13current_concurrency\x18\x02 \x01(\x05R\x12currentConcurrency\x12\x12\n" +
	"\x04load\x18\x03 \x01(\x01R\x04load\"/\n" +
	"\fPingResponse\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\"\xc0\x02\n" +
	"\x19CodespaceOperationPayload\x12#\n" +
	"\rinstance_name\x18\x01 \x01(\tR\finstanceName\x12#\n" +
	"\rinstance_type\x18\x02 \x01(\tR\finstanceType\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12'\n" +
	"\x0fresource_preset\x18\x04 \x01(\tR\x0eresourcePreset\x12\x19\n" +
	"\brepo_url\x18\x05 \x01(\tR\arepoUrl\x12$\n" +
	"\x0erepo_full_name\x18\x06 \x01(\tR\frepoFullName\x12\x1b\n" +
	"\tstart_ref\x18\a \x01(\tR\bstartRef\x12\x1b\n" +
	"\tstart_sha\x18\b \x01(\tR\bstartSha\x12\x1f\n" +
	"\vinit_script\x18\t \x01(\tR\n" +
	"initScript\"\x8e\x02\n" +
	"\x12CodespaceOperation\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12!\n" +
	"\fcodespace_id\x18\x02 \x01(\tR\vcodespaceId\x12/\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1b.codespace.v1.OperationTypeR\x04type\x12A\n" +
	"\apayload\x18\x04 \x01(\v2'.codespace.v1.CodespaceOperationPayloadR\apayload\x12%\n" +
	"\x0elease_deadline\x18\x05 \x01(\x03R\rleaseDeadline\x12!\n" +
	"\foperation_id\x18\x06 \x01(\tR\voperationId\".\n" +
	"\x10FetchTaskRequest\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x05R\bcapacity\"K\n" +
	"\x11FetchTaskResponse\x126\n" +
	"\x05tasks\x18\x01 \x03(\v2 .codespace.v1.CodespaceOperationR\x05tasks\"K\n" +
	"\n" +
	"TaskResult\x12#\n" +
	"\rinstance_name\x18\x01 \x01(\tR\finstanceName\x12\x18\n" +
	"\aworkdir\x18\x02 \x01(\tR\aworkdir\"\xce\x01\n" +
	"\x11FinishTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.codespace.v1.OperationStatusR\x06status\x120\n" +
	"\x06result\x18\x03 \x01(\v2\x18.codespace.v1.TaskResultR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12!\n" +
	"\foperation_id\x18\x05 \x01(\tR\voperationId\"\x14\n" +
	"\x12FinishTaskResponse\"\xdb\x01\n" +
	"\x1cReportCodespaceStatusRequest\x12!\n" +
	"\fcodespace_id\x18\x01 \x01(\tR\vcodespaceId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.codespace.v1.CodespaceStatusR\x06status\x12(\n" +
	"\x10last_active_unix\x18\x03 \x01(\x03R\x0elastActiveUnix\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12!\n" +
	"\foperation_id\x18\x05 \x01(\tR\voperationId\"\x1f\n" +
	"\x1dReportCodespaceStatusResponse\"\x84\x02\n" +
	"\rCodespacePort\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12<\n" +
	"\n" +
	"visibility\x18\x04 \x01(\x0e2\x1c.codespace.v1.PortVisibilityR\n" +
	"visibility\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"public_url\x18\x06 \x01(\tR\tpublicUrl\x120\n" +
	"\x06status\x18\a \x01(\x0e2\x18.codespace.v1.PortStatusR\x06status\"\x96\x01\n" +
	"\x1bReportCodespacePortsRequest\x12!\n" +
	"\fcodespace_id\x18\x01 \x01(\tR\vcodespaceId\x121\n" +
	"\x05ports\x18\x02 \x03(\v2\x1b.codespace.v1.CodespacePortR\x05ports\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\"\x1e\n" +
	"\x1cReportCodespacePortsResponse\"^\n" +
	"\x16RequestGitTokenRequest\x12!\n" +
	"\fcodespace_id\x18\x01 \x01(\tR\vcodespaceId\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\"j\n" +
	"\x17RequestGitTokenResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"u\n" +
	"\x15RevokeGitTokenRequest\x12!\n" +
	"\fcodespace_id\x18\x01 \x01(\tR\vcodespaceId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\"\x18\n" +
	"\x16RevokeGitTokenResponse\"M\n" +
	"\x1bValidateAccessTicketRequest\x12\x16\n" +
	"\x06ticket\x18\x01 \x01(\tR\x06ticket\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"\xc0\x01\n" +
	"\x1cValidateAccessTicketResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12!\n" +
	"\fcodespace_id\x18\x03 \x01(\tR\vcodespaceId\x12\x17\n" +
	"\arepo_id\x18\x04 \x01(\x03R\x06repoId\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\"\xa1\x01\n" +
	"\x10AppendLogRequest\x12!\n" +
	"\fcodespace_id\x18\x01 \x01(\tR\vcodespaceId\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"/\n" +
	"\x11AppendLogResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x03R\bsequence*\x83\x01\n" +
	"\rManagerStatus\x12\x1e\n" +
	"\x1aMANAGER_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15MANAGER_STATUS_ONLINE\x10\x01\x12\x1a\n" +
	"\x16MANAGER_STATUS_OFFLINE\x10\x02\x12\x1b\n" +
	"\x17MANAGER_STATUS_DISABLED\x10\x03*\xec\x01\n" +
	"\x0fCodespaceStatus\x12 \n" +
	"\x1cCODESPACE_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dCODESPACE_STATUS_INITIALIZING\x10\x01\x12\x1c\n" +
	"\x18CODESPACE_STATUS_RUNNING\x10\x02\x12\x1c\n" +
	"\x18CODESPACE_STATUS_STOPPED\x10\x03\x12\x1d\n" +
	"\x19CODESPACE_STATUS_STOPPING\x10\x04\x12\x1d\n" +
	"\x19CODESPACE_STATUS_DELETING\x10\x05\x12\x1a\n" +
	"\x16CODESPACE_STATUS_ERROR\x10\x06*\x99\x01\n" +
	"\rOperationType\x12\x1e\n" +
	"\x1aOPERATION_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15OPERATION_TYPE_CREATE\x10\x01\x12\x19\n" +
	"\x15OPERATION_TYPE_RESUME\x10\x02\x12\x17\n" +
	"\x13OPERATION_TYPE_STOP\x10\x03\x12\x19\n" +
	"\x15OPERATION_TYPE_DELETE\x10\x04*\xe8\x01\n" +
	"\x0fOperationStatus\x12 \n" +
	"\x1cOPERATION_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17OPERATION_STATUS_QUEUED\x10\x01\x12\x1b\n" +
	"\x17OPERATION_STATUS_LEASED\x10\x02\x12\x1c\n" +
	"\x18OPERATION_STATUS_RUNNING\x10\x03\x12\x1e\n" +
	"\x1aOPERATION_STATUS_SUCCEEDED\x10\x04\x12\x1b\n" +
	"\x17OPERATION_STATUS_FAILED\x10\x05\x12\x1e\n" +
	"\x1aOPERATION_STATUS_CANCELLED\x10\x06*\x83\x01\n" +
	"\x0ePortVisibility\x12\x1f\n" +
	"\x1bPORT_VISIBILITY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PORT_VISIBILITY_PRIVATE\x10\x01\x12\x17\n" +
	"\x13PORT_VISIBILITY_ORG\x10\x02\x12\x1a\n" +
	"\x16PORT_VISIBILITY_PUBLIC\x10\x03*\x8b\x01\n" +
	"\n" +
	"PortStatus\x12\x1b\n" +
	"\x17PORT_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PORT_STATUS_ACTIVE\x10\x01\x12\x18\n" +
	"\x14PORT_STATUS_INACTIVE\x10\x02\x12\x15\n" +
	"\x11PORT_STATUS_ERROR\x10\x03\x12\x17\n" +
	"\x13PORT_STATUS_DELETED\x10\x04B7Z5gitea.dev/codespace-proto-go/codespace/v1;codespacev1b\x06proto3"

var (
	file_codespace_v1_types_proto_rawDescOnce sync.Once
	file_codespace_v1_types_proto_rawDescData []byte
)

func file_codespace_v1_types_proto_rawDescGZIP() []byte {
	file_codespace_v1_types_proto_rawDescOnce.Do(func() {
		file_codespace_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codespace_v1_types_proto_rawDesc), len(file_codespace_v1_types_proto_rawDesc)))
	})
	return file_codespace_v1_types_proto_rawDescData
}

var file_codespace_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_codespace_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_codespace_v1_types_proto_goTypes = []any{
	(ManagerStatus)(0),                    // 0: codespace.v1.ManagerStatus
	(CodespaceStatus)(0),                  // 1: codespace.v1.CodespaceStatus
	(OperationType)(0),                    // 2: codespace.v1.OperationType
	(OperationStatus)(0),                  // 3: codespace.v1.OperationStatus
	(PortVisibility)(0),                   // 4: codespace.v1.PortVisibility
	(PortStatus)(0),                       // 5: codespace.v1.PortStatus
	(*ManagerFeatures)(nil),               // 6: codespace.v1.ManagerFeatures
	(*ResourcePreset)(nil),                // 7: codespace.v1.ResourcePreset
	(*ManagerCapabilities)(nil),           // 8: codespace.v1.ManagerCapabilities
	(*RegisterManagerRequest)(nil),        // 9: codespace.v1.RegisterManagerRequest
	(*RegisterManagerResponse)(nil),       // 10: codespace.v1.RegisterManagerResponse
	(*DeclareManagerRequest)(nil),         // 11: codespace.v1.DeclareManagerRequest
	(*DeclareManagerResponse)(nil),        // 12: codespace.v1.DeclareManagerResponse
	(*PingRequest)(nil),                   // 13: codespace.v1.PingRequest
	(*PingResponse)(nil),                  // 14: codespace.v1.PingResponse
	(*CodespaceOperationPayload)(nil),     // 15: codespace.v1.CodespaceOperationPayload
	(*CodespaceOperation)(nil),            // 16: codespace.v1.CodespaceOperation
	(*FetchTaskRequest)(nil),              // 17: codespace.v1.FetchTaskRequest
	(*FetchTaskResponse)(nil),             // 18: codespace.v1.FetchTaskResponse
	(*TaskResult)(nil),                    // 19: codespace.v1.TaskResult
	(*FinishTaskRequest)(nil),             // 20: codespace.v1.FinishTaskRequest
	(*FinishTaskResponse)(nil),            // 21: codespace.v1.FinishTaskResponse
	(*ReportCodespaceStatusRequest)(nil),  // 22: codespace.v1.ReportCodespaceStatusRequest
	(*ReportCodespaceStatusResponse)(nil), // 23: codespace.v1.ReportCodespaceStatusResponse
	(*CodespacePort)(nil),                 // 24: codespace.v1.CodespacePort
	(*ReportCodespacePortsRequest)(nil),   // 25: codespace.v1.ReportCodespacePortsRequest
	(*ReportCodespacePortsResponse)(nil),  // 26: codespace.v1.ReportCodespacePortsResponse
	(*RequestGitTokenRequest)(nil),        // 27: codespace.v1.RequestGitTokenRequest
	(*RequestGitTokenResponse)(nil),       // 28: codespace.v1.RequestGitTokenResponse
	(*RevokeGitTokenRequest)(nil),         // 29: codespace.v1.RevokeGitTokenRequest
	(*RevokeGitTokenResponse)(nil),        // 30: codespace.v1.RevokeGitTokenResponse
	(*ValidateAccessTicketRequest)(nil),   // 31: codespace.v1.ValidateAccessTicketRequest
	(*ValidateAccessTicketResponse)(nil),  // 32: codespace.v1.ValidateAccessTicketResponse
	(*AppendLogRequest)(nil),              // 33: codespace.v1.AppendLogRequest
	(*AppendLogResponse)(nil),             // 34: codespace.v1.AppendLogResponse
}
var file_codespace_v1_types_proto_depIdxs = []int32{
	7,  // 0: codespace.v1.ManagerCapabilities.resource_presets:type_name -> codespace.v1.ResourcePreset
	6,  // 1: codespace.v1.ManagerCapabilities.features:type_name -> codespace.v1.ManagerFeatures
	8,  // 2: codespace.v1.RegisterManagerRequest.capabilities:type_name -> codespace.v1.ManagerCapabilities
	8,  // 3: codespace.v1.DeclareManagerRequest.capabilities:type_name -> codespace.v1.ManagerCapabilities
	0,  // 4: codespace.v1.PingRequest.status:type_name -> codespace.v1.ManagerStatus
	2,  // 5: codespace.v1.CodespaceOperation.type:type_name -> codespace.v1.OperationType
	15, // 6: codespace.v1.CodespaceOperation.payload:type_name -> codespace.v1.CodespaceOperationPayload
	16, // 7: codespace.v1.FetchTaskResponse.tasks:type_name -> codespace.v1.CodespaceOperation
	3,  // 8: codespace.v1.FinishTaskRequest.status:type_name -> codespace.v1.OperationStatus
	19, // 9: codespace.v1.FinishTaskRequest.result:type_name -> codespace.v1.TaskResult
	1,  // 10: codespace.v1.ReportCodespaceStatusRequest.status:type_name -> codespace.v1.CodespaceStatus
	4,  // 11: codespace.v1.CodespacePort.visibility:type_name -> codespace.v1.PortVisibility
	5,  // 12: codespace.v1.CodespacePort.status:type_name -> codespace.v1.PortStatus
	24, // 13: codespace.v1.ReportCodespacePortsRequest.ports:type_name -> codespace.v1.CodespacePort
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_codespace_v1_types_proto_init() }
func file_codespace_v1_types_proto_init() {
	if File_codespace_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codespace_v1_types_proto_rawDesc), len(file_codespace_v1_types_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codespace_v1_types_proto_goTypes,
		DependencyIndexes: file_codespace_v1_types_proto_depIdxs,
		EnumInfos:         file_codespace_v1_types_proto_enumTypes,
		MessageInfos:      file_codespace_v1_types_proto_msgTypes,
	}.Build()
	File_codespace_v1_types_proto = out.File
	file_codespace_v1_types_proto_goTypes = nil
	file_codespace_v1_types_proto_depIdxs = nil
}
