// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: component/v1/service.proto

package componentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "gitea.dev/codespace-proto-go/component/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ComponentServiceName is the fully-qualified name of the ComponentService service.
	ComponentServiceName = "component.v1.ComponentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ComponentServiceGetGatewayConfigProcedure is the fully-qualified name of the ComponentService's
	// GetGatewayConfig RPC.
	ComponentServiceGetGatewayConfigProcedure = "/component.v1.ComponentService/GetGatewayConfig"
	// ComponentServiceWatchGatewayConfigProcedure is the fully-qualified name of the ComponentService's
	// WatchGatewayConfig RPC.
	ComponentServiceWatchGatewayConfigProcedure = "/component.v1.ComponentService/WatchGatewayConfig"
	// ComponentServiceReportGatewayActivityProcedure is the fully-qualified name of the
	// ComponentService's ReportGatewayActivity RPC.
	ComponentServiceReportGatewayActivityProcedure = "/component.v1.ComponentService/ReportGatewayActivity"
	// ComponentServiceGetCacheProcedure is the fully-qualified name of the ComponentService's GetCache
	// RPC.
	ComponentServiceGetCacheProcedure = "/component.v1.ComponentService/GetCache"
	// ComponentServiceClaimCacheProcedure is the fully-qualified name of the ComponentService's
	// ClaimCache RPC.
	ComponentServiceClaimCacheProcedure = "/component.v1.ComponentService/ClaimCache"
	// ComponentServiceHeartbeatCacheProcedure is the fully-qualified name of the ComponentService's
	// HeartbeatCache RPC.
	ComponentServiceHeartbeatCacheProcedure = "/component.v1.ComponentService/HeartbeatCache"
	// ComponentServiceReleaseCacheProcedure is the fully-qualified name of the ComponentService's
	// ReleaseCache RPC.
	ComponentServiceReleaseCacheProcedure = "/component.v1.ComponentService/ReleaseCache"
	// ComponentServiceVerifyCacheTokenProcedure is the fully-qualified name of the ComponentService's
	// VerifyCacheToken RPC.
	ComponentServiceVerifyCacheTokenProcedure = "/component.v1.ComponentService/VerifyCacheToken"
	// ComponentServiceBeginCacheGCProcedure is the fully-qualified name of the ComponentService's
	// BeginCacheGC RPC.
	ComponentServiceBeginCacheGCProcedure = "/component.v1.ComponentService/BeginCacheGC"
	// ComponentServiceCompleteCacheGCProcedure is the fully-qualified name of the ComponentService's
	// CompleteCacheGC RPC.
	ComponentServiceCompleteCacheGCProcedure = "/component.v1.ComponentService/CompleteCacheGC"
)

// ComponentServiceClient is a client for the component.v1.ComponentService service.
type ComponentServiceClient interface {
	// GetGatewayConfig returns a complete Gateway configuration snapshot.
	GetGatewayConfig(context.Context, *connect.Request[v1.GetGatewayConfigRequest]) (*connect.Response[v1.GetGatewayConfigResponse], error)
	// WatchGatewayConfig waits for configuration or runtime changes after a revision.
	WatchGatewayConfig(context.Context, *connect.Request[v1.WatchGatewayConfigRequest]) (*connect.Response[v1.WatchGatewayConfigResponse], error)
	// ReportGatewayActivity publishes live Gateway session counts.
	ReportGatewayActivity(context.Context, *connect.Request[v1.ReportGatewayActivityRequest]) (*connect.Response[v1.ReportGatewayActivityResponse], error)
	// GetCache returns the configuration and private key for one cache.
	GetCache(context.Context, *connect.Request[v1.GetCacheRequest]) (*connect.Response[v1.GetCacheResponse], error)
	// ClaimCache claims one cache service instance.
	ClaimCache(context.Context, *connect.Request[v1.ClaimCacheRequest]) (*connect.Response[v1.ClaimCacheResponse], error)
	// HeartbeatCache publishes cache health while the owner lease is active.
	HeartbeatCache(context.Context, *connect.Request[v1.HeartbeatCacheRequest]) (*connect.Response[v1.HeartbeatCacheResponse], error)
	// ReleaseCache releases one cache service owner.
	ReleaseCache(context.Context, *connect.Request[v1.ReleaseCacheRequest]) (*connect.Response[v1.ReleaseCacheResponse], error)
	// VerifyCacheToken verifies a cache build credential.
	VerifyCacheToken(context.Context, *connect.Request[v1.VerifyCacheTokenRequest]) (*connect.Response[v1.VerifyCacheTokenResponse], error)
	// BeginCacheGC grants one cache instance permission to collect local data.
	BeginCacheGC(context.Context, *connect.Request[v1.BeginCacheGCRequest]) (*connect.Response[v1.BeginCacheGCResponse], error)
	// CompleteCacheGC records the result of one granted collection pass.
	CompleteCacheGC(context.Context, *connect.Request[v1.CompleteCacheGCRequest]) (*connect.Response[v1.CompleteCacheGCResponse], error)
}

// NewComponentServiceClient constructs a client for the component.v1.ComponentService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewComponentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ComponentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	componentServiceMethods := v1.File_component_v1_service_proto.Services().ByName("ComponentService").Methods()
	return &componentServiceClient{
		getGatewayConfig: connect.NewClient[v1.GetGatewayConfigRequest, v1.GetGatewayConfigResponse](
			httpClient,
			baseURL+ComponentServiceGetGatewayConfigProcedure,
			connect.WithSchema(componentServiceMethods.ByName("GetGatewayConfig")),
			connect.WithClientOptions(opts...),
		),
		watchGatewayConfig: connect.NewClient[v1.WatchGatewayConfigRequest, v1.WatchGatewayConfigResponse](
			httpClient,
			baseURL+ComponentServiceWatchGatewayConfigProcedure,
			connect.WithSchema(componentServiceMethods.ByName("WatchGatewayConfig")),
			connect.WithClientOptions(opts...),
		),
		reportGatewayActivity: connect.NewClient[v1.ReportGatewayActivityRequest, v1.ReportGatewayActivityResponse](
			httpClient,
			baseURL+ComponentServiceReportGatewayActivityProcedure,
			connect.WithSchema(componentServiceMethods.ByName("ReportGatewayActivity")),
			connect.WithClientOptions(opts...),
		),
		getCache: connect.NewClient[v1.GetCacheRequest, v1.GetCacheResponse](
			httpClient,
			baseURL+ComponentServiceGetCacheProcedure,
			connect.WithSchema(componentServiceMethods.ByName("GetCache")),
			connect.WithClientOptions(opts...),
		),
		claimCache: connect.NewClient[v1.ClaimCacheRequest, v1.ClaimCacheResponse](
			httpClient,
			baseURL+ComponentServiceClaimCacheProcedure,
			connect.WithSchema(componentServiceMethods.ByName("ClaimCache")),
			connect.WithClientOptions(opts...),
		),
		heartbeatCache: connect.NewClient[v1.HeartbeatCacheRequest, v1.HeartbeatCacheResponse](
			httpClient,
			baseURL+ComponentServiceHeartbeatCacheProcedure,
			connect.WithSchema(componentServiceMethods.ByName("HeartbeatCache")),
			connect.WithClientOptions(opts...),
		),
		releaseCache: connect.NewClient[v1.ReleaseCacheRequest, v1.ReleaseCacheResponse](
			httpClient,
			baseURL+ComponentServiceReleaseCacheProcedure,
			connect.WithSchema(componentServiceMethods.ByName("ReleaseCache")),
			connect.WithClientOptions(opts...),
		),
		verifyCacheToken: connect.NewClient[v1.VerifyCacheTokenRequest, v1.VerifyCacheTokenResponse](
			httpClient,
			baseURL+ComponentServiceVerifyCacheTokenProcedure,
			connect.WithSchema(componentServiceMethods.ByName("VerifyCacheToken")),
			connect.WithClientOptions(opts...),
		),
		beginCacheGC: connect.NewClient[v1.BeginCacheGCRequest, v1.BeginCacheGCResponse](
			httpClient,
			baseURL+ComponentServiceBeginCacheGCProcedure,
			connect.WithSchema(componentServiceMethods.ByName("BeginCacheGC")),
			connect.WithClientOptions(opts...),
		),
		completeCacheGC: connect.NewClient[v1.CompleteCacheGCRequest, v1.CompleteCacheGCResponse](
			httpClient,
			baseURL+ComponentServiceCompleteCacheGCProcedure,
			connect.WithSchema(componentServiceMethods.ByName("CompleteCacheGC")),
			connect.WithClientOptions(opts...),
		),
	}
}

// componentServiceClient implements ComponentServiceClient.
type componentServiceClient struct {
	getGatewayConfig      *connect.Client[v1.GetGatewayConfigRequest, v1.GetGatewayConfigResponse]
	watchGatewayConfig    *connect.Client[v1.WatchGatewayConfigRequest, v1.WatchGatewayConfigResponse]
	reportGatewayActivity *connect.Client[v1.ReportGatewayActivityRequest, v1.ReportGatewayActivityResponse]
	getCache              *connect.Client[v1.GetCacheRequest, v1.GetCacheResponse]
	claimCache            *connect.Client[v1.ClaimCacheRequest, v1.ClaimCacheResponse]
	heartbeatCache        *connect.Client[v1.HeartbeatCacheRequest, v1.HeartbeatCacheResponse]
	releaseCache          *connect.Client[v1.ReleaseCacheRequest, v1.ReleaseCacheResponse]
	verifyCacheToken      *connect.Client[v1.VerifyCacheTokenRequest, v1.VerifyCacheTokenResponse]
	beginCacheGC          *connect.Client[v1.BeginCacheGCRequest, v1.BeginCacheGCResponse]
	completeCacheGC       *connect.Client[v1.CompleteCacheGCRequest, v1.CompleteCacheGCResponse]
}

// GetGatewayConfig calls component.v1.ComponentService.GetGatewayConfig.
func (c *componentServiceClient) GetGatewayConfig(ctx context.Context, req *connect.Request[v1.GetGatewayConfigRequest]) (*connect.Response[v1.GetGatewayConfigResponse], error) {
	return c.getGatewayConfig.CallUnary(ctx, req)
}

// WatchGatewayConfig calls component.v1.ComponentService.WatchGatewayConfig.
func (c *componentServiceClient) WatchGatewayConfig(ctx context.Context, req *connect.Request[v1.WatchGatewayConfigRequest]) (*connect.Response[v1.WatchGatewayConfigResponse], error) {
	return c.watchGatewayConfig.CallUnary(ctx, req)
}

// ReportGatewayActivity calls component.v1.ComponentService.ReportGatewayActivity.
func (c *componentServiceClient) ReportGatewayActivity(ctx context.Context, req *connect.Request[v1.ReportGatewayActivityRequest]) (*connect.Response[v1.ReportGatewayActivityResponse], error) {
	return c.reportGatewayActivity.CallUnary(ctx, req)
}

// GetCache calls component.v1.ComponentService.GetCache.
func (c *componentServiceClient) GetCache(ctx context.Context, req *connect.Request[v1.GetCacheRequest]) (*connect.Response[v1.GetCacheResponse], error) {
	return c.getCache.CallUnary(ctx, req)
}

// ClaimCache calls component.v1.ComponentService.ClaimCache.
func (c *componentServiceClient) ClaimCache(ctx context.Context, req *connect.Request[v1.ClaimCacheRequest]) (*connect.Response[v1.ClaimCacheResponse], error) {
	return c.claimCache.CallUnary(ctx, req)
}

// HeartbeatCache calls component.v1.ComponentService.HeartbeatCache.
func (c *componentServiceClient) HeartbeatCache(ctx context.Context, req *connect.Request[v1.HeartbeatCacheRequest]) (*connect.Response[v1.HeartbeatCacheResponse], error) {
	return c.heartbeatCache.CallUnary(ctx, req)
}

// ReleaseCache calls component.v1.ComponentService.ReleaseCache.
func (c *componentServiceClient) ReleaseCache(ctx context.Context, req *connect.Request[v1.ReleaseCacheRequest]) (*connect.Response[v1.ReleaseCacheResponse], error) {
	return c.releaseCache.CallUnary(ctx, req)
}

// VerifyCacheToken calls component.v1.ComponentService.VerifyCacheToken.
func (c *componentServiceClient) VerifyCacheToken(ctx context.Context, req *connect.Request[v1.VerifyCacheTokenRequest]) (*connect.Response[v1.VerifyCacheTokenResponse], error) {
	return c.verifyCacheToken.CallUnary(ctx, req)
}

// BeginCacheGC calls component.v1.ComponentService.BeginCacheGC.
func (c *componentServiceClient) BeginCacheGC(ctx context.Context, req *connect.Request[v1.BeginCacheGCRequest]) (*connect.Response[v1.BeginCacheGCResponse], error) {
	return c.beginCacheGC.CallUnary(ctx, req)
}

// CompleteCacheGC calls component.v1.ComponentService.CompleteCacheGC.
func (c *componentServiceClient) CompleteCacheGC(ctx context.Context, req *connect.Request[v1.CompleteCacheGCRequest]) (*connect.Response[v1.CompleteCacheGCResponse], error) {
	return c.completeCacheGC.CallUnary(ctx, req)
}

// ComponentServiceHandler is an implementation of the component.v1.ComponentService service.
type ComponentServiceHandler interface {
	// GetGatewayConfig returns a complete Gateway configuration snapshot.
	GetGatewayConfig(context.Context, *connect.Request[v1.GetGatewayConfigRequest]) (*connect.Response[v1.GetGatewayConfigResponse], error)
	// WatchGatewayConfig waits for configuration or runtime changes after a revision.
	WatchGatewayConfig(context.Context, *connect.Request[v1.WatchGatewayConfigRequest]) (*connect.Response[v1.WatchGatewayConfigResponse], error)
	// ReportGatewayActivity publishes live Gateway session counts.
	ReportGatewayActivity(context.Context, *connect.Request[v1.ReportGatewayActivityRequest]) (*connect.Response[v1.ReportGatewayActivityResponse], error)
	// GetCache returns the configuration and private key for one cache.
	GetCache(context.Context, *connect.Request[v1.GetCacheRequest]) (*connect.Response[v1.GetCacheResponse], error)
	// ClaimCache claims one cache service instance.
	ClaimCache(context.Context, *connect.Request[v1.ClaimCacheRequest]) (*connect.Response[v1.ClaimCacheResponse], error)
	// HeartbeatCache publishes cache health while the owner lease is active.
	HeartbeatCache(context.Context, *connect.Request[v1.HeartbeatCacheRequest]) (*connect.Response[v1.HeartbeatCacheResponse], error)
	// ReleaseCache releases one cache service owner.
	ReleaseCache(context.Context, *connect.Request[v1.ReleaseCacheRequest]) (*connect.Response[v1.ReleaseCacheResponse], error)
	// VerifyCacheToken verifies a cache build credential.
	VerifyCacheToken(context.Context, *connect.Request[v1.VerifyCacheTokenRequest]) (*connect.Response[v1.VerifyCacheTokenResponse], error)
	// BeginCacheGC grants one cache instance permission to collect local data.
	BeginCacheGC(context.Context, *connect.Request[v1.BeginCacheGCRequest]) (*connect.Response[v1.BeginCacheGCResponse], error)
	// CompleteCacheGC records the result of one granted collection pass.
	CompleteCacheGC(context.Context, *connect.Request[v1.CompleteCacheGCRequest]) (*connect.Response[v1.CompleteCacheGCResponse], error)
}

// NewComponentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewComponentServiceHandler(svc ComponentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	componentServiceMethods := v1.File_component_v1_service_proto.Services().ByName("ComponentService").Methods()
	componentServiceGetGatewayConfigHandler := connect.NewUnaryHandler(
		ComponentServiceGetGatewayConfigProcedure,
		svc.GetGatewayConfig,
		connect.WithSchema(componentServiceMethods.ByName("GetGatewayConfig")),
		connect.WithHandlerOptions(opts...),
	)
	componentServiceWatchGatewayConfigHandler := connect.NewUnaryHandler(
		ComponentServiceWatchGatewayConfigProcedure,
		svc.WatchGatewayConfig,
		connect.WithSchema(componentServiceMethods.ByName("WatchGatewayConfig")),
		connect.WithHandlerOptions(opts...),
	)
	componentServiceReportGatewayActivityHandler := connect.NewUnaryHandler(
		ComponentServiceReportGatewayActivityProcedure,
		svc.ReportGatewayActivity,
		connect.WithSchema(componentServiceMethods.ByName("ReportGatewayActivity")),
		connect.WithHandlerOptions(opts...),
	)
	componentServiceGetCacheHandler := connect.NewUnaryHandler(
		ComponentServiceGetCacheProcedure,
		svc.GetCache,
		connect.WithSchema(componentServiceMethods.ByName("GetCache")),
		connect.WithHandlerOptions(opts...),
	)
	componentServiceClaimCacheHandler := connect.NewUnaryHandler(
		ComponentServiceClaimCacheProcedure,
		svc.ClaimCache,
		connect.WithSchema(componentServiceMethods.ByName("ClaimCache")),
		connect.WithHandlerOptions(opts...),
	)
	componentServiceHeartbeatCacheHandler := connect.NewUnaryHandler(
		ComponentServiceHeartbeatCacheProcedure,
		svc.HeartbeatCache,
		connect.WithSchema(componentServiceMethods.ByName("HeartbeatCache")),
		connect.WithHandlerOptions(opts...),
	)
	componentServiceReleaseCacheHandler := connect.NewUnaryHandler(
		ComponentServiceReleaseCacheProcedure,
		svc.ReleaseCache,
		connect.WithSchema(componentServiceMethods.ByName("ReleaseCache")),
		connect.WithHandlerOptions(opts...),
	)
	componentServiceVerifyCacheTokenHandler := connect.NewUnaryHandler(
		ComponentServiceVerifyCacheTokenProcedure,
		svc.VerifyCacheToken,
		connect.WithSchema(componentServiceMethods.ByName("VerifyCacheToken")),
		connect.WithHandlerOptions(opts...),
	)
	componentServiceBeginCacheGCHandler := connect.NewUnaryHandler(
		ComponentServiceBeginCacheGCProcedure,
		svc.BeginCacheGC,
		connect.WithSchema(componentServiceMethods.ByName("BeginCacheGC")),
		connect.WithHandlerOptions(opts...),
	)
	componentServiceCompleteCacheGCHandler := connect.NewUnaryHandler(
		ComponentServiceCompleteCacheGCProcedure,
		svc.CompleteCacheGC,
		connect.WithSchema(componentServiceMethods.ByName("CompleteCacheGC")),
		connect.WithHandlerOptions(opts...),
	)
	return "/component.v1.ComponentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ComponentServiceGetGatewayConfigProcedure:
			componentServiceGetGatewayConfigHandler.ServeHTTP(w, r)
		case ComponentServiceWatchGatewayConfigProcedure:
			componentServiceWatchGatewayConfigHandler.ServeHTTP(w, r)
		case ComponentServiceReportGatewayActivityProcedure:
			componentServiceReportGatewayActivityHandler.ServeHTTP(w, r)
		case ComponentServiceGetCacheProcedure:
			componentServiceGetCacheHandler.ServeHTTP(w, r)
		case ComponentServiceClaimCacheProcedure:
			componentServiceClaimCacheHandler.ServeHTTP(w, r)
		case ComponentServiceHeartbeatCacheProcedure:
			componentServiceHeartbeatCacheHandler.ServeHTTP(w, r)
		case ComponentServiceReleaseCacheProcedure:
			componentServiceReleaseCacheHandler.ServeHTTP(w, r)
		case ComponentServiceVerifyCacheTokenProcedure:
			componentServiceVerifyCacheTokenHandler.ServeHTTP(w, r)
		case ComponentServiceBeginCacheGCProcedure:
			componentServiceBeginCacheGCHandler.ServeHTTP(w, r)
		case ComponentServiceCompleteCacheGCProcedure:
			componentServiceCompleteCacheGCHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedComponentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedComponentServiceHandler struct{}

func (UnimplementedComponentServiceHandler) GetGatewayConfig(context.Context, *connect.Request[v1.GetGatewayConfigRequest]) (*connect.Response[v1.GetGatewayConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("component.v1.ComponentService.GetGatewayConfig is not implemented"))
}

func (UnimplementedComponentServiceHandler) WatchGatewayConfig(context.Context, *connect.Request[v1.WatchGatewayConfigRequest]) (*connect.Response[v1.WatchGatewayConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("component.v1.ComponentService.WatchGatewayConfig is not implemented"))
}

func (UnimplementedComponentServiceHandler) ReportGatewayActivity(context.Context, *connect.Request[v1.ReportGatewayActivityRequest]) (*connect.Response[v1.ReportGatewayActivityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("component.v1.ComponentService.ReportGatewayActivity is not implemented"))
}

func (UnimplementedComponentServiceHandler) GetCache(context.Context, *connect.Request[v1.GetCacheRequest]) (*connect.Response[v1.GetCacheResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("component.v1.ComponentService.GetCache is not implemented"))
}

func (UnimplementedComponentServiceHandler) ClaimCache(context.Context, *connect.Request[v1.ClaimCacheRequest]) (*connect.Response[v1.ClaimCacheResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("component.v1.ComponentService.ClaimCache is not implemented"))
}

func (UnimplementedComponentServiceHandler) HeartbeatCache(context.Context, *connect.Request[v1.HeartbeatCacheRequest]) (*connect.Response[v1.HeartbeatCacheResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("component.v1.ComponentService.HeartbeatCache is not implemented"))
}

func (UnimplementedComponentServiceHandler) ReleaseCache(context.Context, *connect.Request[v1.ReleaseCacheRequest]) (*connect.Response[v1.ReleaseCacheResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("component.v1.ComponentService.ReleaseCache is not implemented"))
}

func (UnimplementedComponentServiceHandler) VerifyCacheToken(context.Context, *connect.Request[v1.VerifyCacheTokenRequest]) (*connect.Response[v1.VerifyCacheTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("component.v1.ComponentService.VerifyCacheToken is not implemented"))
}

func (UnimplementedComponentServiceHandler) BeginCacheGC(context.Context, *connect.Request[v1.BeginCacheGCRequest]) (*connect.Response[v1.BeginCacheGCResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("component.v1.ComponentService.BeginCacheGC is not implemented"))
}

func (UnimplementedComponentServiceHandler) CompleteCacheGC(context.Context, *connect.Request[v1.CompleteCacheGCRequest]) (*connect.Response[v1.CompleteCacheGCResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("component.v1.ComponentService.CompleteCacheGC is not implemented"))
}
