// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: codespace/v1/service.proto

package codespacev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "gitea.dev/codespace-proto-go/codespace/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CodespaceServiceName is the fully-qualified name of the CodespaceService service.
	CodespaceServiceName = "codespace.v1.CodespaceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CodespaceServiceRegisterManagerProcedure is the fully-qualified name of the CodespaceService's
	// RegisterManager RPC.
	CodespaceServiceRegisterManagerProcedure = "/codespace.v1.CodespaceService/RegisterManager"
	// CodespaceServiceDeclareManagerProcedure is the fully-qualified name of the CodespaceService's
	// DeclareManager RPC.
	CodespaceServiceDeclareManagerProcedure = "/codespace.v1.CodespaceService/DeclareManager"
	// CodespaceServicePingProcedure is the fully-qualified name of the CodespaceService's Ping RPC.
	CodespaceServicePingProcedure = "/codespace.v1.CodespaceService/Ping"
	// CodespaceServiceFetchTaskProcedure is the fully-qualified name of the CodespaceService's
	// FetchTask RPC.
	CodespaceServiceFetchTaskProcedure = "/codespace.v1.CodespaceService/FetchTask"
	// CodespaceServiceAppendLogProcedure is the fully-qualified name of the CodespaceService's
	// AppendLog RPC.
	CodespaceServiceAppendLogProcedure = "/codespace.v1.CodespaceService/AppendLog"
	// CodespaceServiceFinishTaskProcedure is the fully-qualified name of the CodespaceService's
	// FinishTask RPC.
	CodespaceServiceFinishTaskProcedure = "/codespace.v1.CodespaceService/FinishTask"
	// CodespaceServiceReportCodespaceStatusProcedure is the fully-qualified name of the
	// CodespaceService's ReportCodespaceStatus RPC.
	CodespaceServiceReportCodespaceStatusProcedure = "/codespace.v1.CodespaceService/ReportCodespaceStatus"
	// CodespaceServiceReportCodespacePortsProcedure is the fully-qualified name of the
	// CodespaceService's ReportCodespacePorts RPC.
	CodespaceServiceReportCodespacePortsProcedure = "/codespace.v1.CodespaceService/ReportCodespacePorts"
	// CodespaceServiceRequestGitTokenProcedure is the fully-qualified name of the CodespaceService's
	// RequestGitToken RPC.
	CodespaceServiceRequestGitTokenProcedure = "/codespace.v1.CodespaceService/RequestGitToken"
	// CodespaceServiceRevokeGitTokenProcedure is the fully-qualified name of the CodespaceService's
	// RevokeGitToken RPC.
	CodespaceServiceRevokeGitTokenProcedure = "/codespace.v1.CodespaceService/RevokeGitToken"
	// CodespaceServiceValidateAccessTicketProcedure is the fully-qualified name of the
	// CodespaceService's ValidateAccessTicket RPC.
	CodespaceServiceValidateAccessTicketProcedure = "/codespace.v1.CodespaceService/ValidateAccessTicket"
)

// CodespaceServiceClient is a client for the codespace.v1.CodespaceService service.
type CodespaceServiceClient interface {
	// RegisterManager exchanges a scope-bound registration token for a manager
	// identity and manager token.
	RegisterManager(context.Context, *connect.Request[v1.RegisterManagerRequest]) (*connect.Response[v1.RegisterManagerResponse], error)
	// DeclareManager updates the authenticated manager's metadata and runtime
	// capabilities after registration.
	DeclareManager(context.Context, *connect.Request[v1.DeclareManagerRequest]) (*connect.Response[v1.DeclareManagerResponse], error)
	// Ping records the authenticated manager heartbeat and load snapshot.
	Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error)
	// FetchTask leases queued tasks assigned to the authenticated manager.
	FetchTask(context.Context, *connect.Request[v1.FetchTaskRequest]) (*connect.Response[v1.FetchTaskResponse], error)
	// AppendLog appends output to the authenticated manager's active operation.
	AppendLog(context.Context, *connect.Request[v1.AppendLogRequest]) (*connect.Response[v1.AppendLogResponse], error)
	// FinishTask records the authenticated manager's result for a leased task.
	FinishTask(context.Context, *connect.Request[v1.FinishTaskRequest]) (*connect.Response[v1.FinishTaskResponse], error)
	// ReportCodespaceStatus records runtime status for a codespace owned by the
	// authenticated manager.
	ReportCodespaceStatus(context.Context, *connect.Request[v1.ReportCodespaceStatusRequest]) (*connect.Response[v1.ReportCodespaceStatusResponse], error)
	// ReportCodespacePorts replaces the visible port set for a codespace owned
	// by the authenticated manager.
	ReportCodespacePorts(context.Context, *connect.Request[v1.ReportCodespacePortsRequest]) (*connect.Response[v1.ReportCodespacePortsResponse], error)
	// RequestGitToken issues a short-lived repository token for a codespace
	// owned by the authenticated manager.
	RequestGitToken(context.Context, *connect.Request[v1.RequestGitTokenRequest]) (*connect.Response[v1.RequestGitTokenResponse], error)
	// RevokeGitToken revokes active repository tokens for a codespace owned by
	// the authenticated manager.
	RevokeGitToken(context.Context, *connect.Request[v1.RevokeGitTokenRequest]) (*connect.Response[v1.RevokeGitTokenResponse], error)
	// ValidateAccessTicket validates a short-lived user access ticket presented
	// to the gateway.
	ValidateAccessTicket(context.Context, *connect.Request[v1.ValidateAccessTicketRequest]) (*connect.Response[v1.ValidateAccessTicketResponse], error)
}

// NewCodespaceServiceClient constructs a client for the codespace.v1.CodespaceService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCodespaceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CodespaceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	codespaceServiceMethods := v1.File_codespace_v1_service_proto.Services().ByName("CodespaceService").Methods()
	return &codespaceServiceClient{
		registerManager: connect.NewClient[v1.RegisterManagerRequest, v1.RegisterManagerResponse](
			httpClient,
			baseURL+CodespaceServiceRegisterManagerProcedure,
			connect.WithSchema(codespaceServiceMethods.ByName("RegisterManager")),
			connect.WithClientOptions(opts...),
		),
		declareManager: connect.NewClient[v1.DeclareManagerRequest, v1.DeclareManagerResponse](
			httpClient,
			baseURL+CodespaceServiceDeclareManagerProcedure,
			connect.WithSchema(codespaceServiceMethods.ByName("DeclareManager")),
			connect.WithClientOptions(opts...),
		),
		ping: connect.NewClient[v1.PingRequest, v1.PingResponse](
			httpClient,
			baseURL+CodespaceServicePingProcedure,
			connect.WithSchema(codespaceServiceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
		fetchTask: connect.NewClient[v1.FetchTaskRequest, v1.FetchTaskResponse](
			httpClient,
			baseURL+CodespaceServiceFetchTaskProcedure,
			connect.WithSchema(codespaceServiceMethods.ByName("FetchTask")),
			connect.WithClientOptions(opts...),
		),
		appendLog: connect.NewClient[v1.AppendLogRequest, v1.AppendLogResponse](
			httpClient,
			baseURL+CodespaceServiceAppendLogProcedure,
			connect.WithSchema(codespaceServiceMethods.ByName("AppendLog")),
			connect.WithClientOptions(opts...),
		),
		finishTask: connect.NewClient[v1.FinishTaskRequest, v1.FinishTaskResponse](
			httpClient,
			baseURL+CodespaceServiceFinishTaskProcedure,
			connect.WithSchema(codespaceServiceMethods.ByName("FinishTask")),
			connect.WithClientOptions(opts...),
		),
		reportCodespaceStatus: connect.NewClient[v1.ReportCodespaceStatusRequest, v1.ReportCodespaceStatusResponse](
			httpClient,
			baseURL+CodespaceServiceReportCodespaceStatusProcedure,
			connect.WithSchema(codespaceServiceMethods.ByName("ReportCodespaceStatus")),
			connect.WithClientOptions(opts...),
		),
		reportCodespacePorts: connect.NewClient[v1.ReportCodespacePortsRequest, v1.ReportCodespacePortsResponse](
			httpClient,
			baseURL+CodespaceServiceReportCodespacePortsProcedure,
			connect.WithSchema(codespaceServiceMethods.ByName("ReportCodespacePorts")),
			connect.WithClientOptions(opts...),
		),
		requestGitToken: connect.NewClient[v1.RequestGitTokenRequest, v1.RequestGitTokenResponse](
			httpClient,
			baseURL+CodespaceServiceRequestGitTokenProcedure,
			connect.WithSchema(codespaceServiceMethods.ByName("RequestGitToken")),
			connect.WithClientOptions(opts...),
		),
		revokeGitToken: connect.NewClient[v1.RevokeGitTokenRequest, v1.RevokeGitTokenResponse](
			httpClient,
			baseURL+CodespaceServiceRevokeGitTokenProcedure,
			connect.WithSchema(codespaceServiceMethods.ByName("RevokeGitToken")),
			connect.WithClientOptions(opts...),
		),
		validateAccessTicket: connect.NewClient[v1.ValidateAccessTicketRequest, v1.ValidateAccessTicketResponse](
			httpClient,
			baseURL+CodespaceServiceValidateAccessTicketProcedure,
			connect.WithSchema(codespaceServiceMethods.ByName("ValidateAccessTicket")),
			connect.WithClientOptions(opts...),
		),
	}
}

// codespaceServiceClient implements CodespaceServiceClient.
type codespaceServiceClient struct {
	registerManager       *connect.Client[v1.RegisterManagerRequest, v1.RegisterManagerResponse]
	declareManager        *connect.Client[v1.DeclareManagerRequest, v1.DeclareManagerResponse]
	ping                  *connect.Client[v1.PingRequest, v1.PingResponse]
	fetchTask             *connect.Client[v1.FetchTaskRequest, v1.FetchTaskResponse]
	appendLog             *connect.Client[v1.AppendLogRequest, v1.AppendLogResponse]
	finishTask            *connect.Client[v1.FinishTaskRequest, v1.FinishTaskResponse]
	reportCodespaceStatus *connect.Client[v1.ReportCodespaceStatusRequest, v1.ReportCodespaceStatusResponse]
	reportCodespacePorts  *connect.Client[v1.ReportCodespacePortsRequest, v1.ReportCodespacePortsResponse]
	requestGitToken       *connect.Client[v1.RequestGitTokenRequest, v1.RequestGitTokenResponse]
	revokeGitToken        *connect.Client[v1.RevokeGitTokenRequest, v1.RevokeGitTokenResponse]
	validateAccessTicket  *connect.Client[v1.ValidateAccessTicketRequest, v1.ValidateAccessTicketResponse]
}

// RegisterManager calls codespace.v1.CodespaceService.RegisterManager.
func (c *codespaceServiceClient) RegisterManager(ctx context.Context, req *connect.Request[v1.RegisterManagerRequest]) (*connect.Response[v1.RegisterManagerResponse], error) {
	return c.registerManager.CallUnary(ctx, req)
}

// DeclareManager calls codespace.v1.CodespaceService.DeclareManager.
func (c *codespaceServiceClient) DeclareManager(ctx context.Context, req *connect.Request[v1.DeclareManagerRequest]) (*connect.Response[v1.DeclareManagerResponse], error) {
	return c.declareManager.CallUnary(ctx, req)
}

// Ping calls codespace.v1.CodespaceService.Ping.
func (c *codespaceServiceClient) Ping(ctx context.Context, req *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// FetchTask calls codespace.v1.CodespaceService.FetchTask.
func (c *codespaceServiceClient) FetchTask(ctx context.Context, req *connect.Request[v1.FetchTaskRequest]) (*connect.Response[v1.FetchTaskResponse], error) {
	return c.fetchTask.CallUnary(ctx, req)
}

// AppendLog calls codespace.v1.CodespaceService.AppendLog.
func (c *codespaceServiceClient) AppendLog(ctx context.Context, req *connect.Request[v1.AppendLogRequest]) (*connect.Response[v1.AppendLogResponse], error) {
	return c.appendLog.CallUnary(ctx, req)
}

// FinishTask calls codespace.v1.CodespaceService.FinishTask.
func (c *codespaceServiceClient) FinishTask(ctx context.Context, req *connect.Request[v1.FinishTaskRequest]) (*connect.Response[v1.FinishTaskResponse], error) {
	return c.finishTask.CallUnary(ctx, req)
}

// ReportCodespaceStatus calls codespace.v1.CodespaceService.ReportCodespaceStatus.
func (c *codespaceServiceClient) ReportCodespaceStatus(ctx context.Context, req *connect.Request[v1.ReportCodespaceStatusRequest]) (*connect.Response[v1.ReportCodespaceStatusResponse], error) {
	return c.reportCodespaceStatus.CallUnary(ctx, req)
}

// ReportCodespacePorts calls codespace.v1.CodespaceService.ReportCodespacePorts.
func (c *codespaceServiceClient) ReportCodespacePorts(ctx context.Context, req *connect.Request[v1.ReportCodespacePortsRequest]) (*connect.Response[v1.ReportCodespacePortsResponse], error) {
	return c.reportCodespacePorts.CallUnary(ctx, req)
}

// RequestGitToken calls codespace.v1.CodespaceService.RequestGitToken.
func (c *codespaceServiceClient) RequestGitToken(ctx context.Context, req *connect.Request[v1.RequestGitTokenRequest]) (*connect.Response[v1.RequestGitTokenResponse], error) {
	return c.requestGitToken.CallUnary(ctx, req)
}

// RevokeGitToken calls codespace.v1.CodespaceService.RevokeGitToken.
func (c *codespaceServiceClient) RevokeGitToken(ctx context.Context, req *connect.Request[v1.RevokeGitTokenRequest]) (*connect.Response[v1.RevokeGitTokenResponse], error) {
	return c.revokeGitToken.CallUnary(ctx, req)
}

// ValidateAccessTicket calls codespace.v1.CodespaceService.ValidateAccessTicket.
func (c *codespaceServiceClient) ValidateAccessTicket(ctx context.Context, req *connect.Request[v1.ValidateAccessTicketRequest]) (*connect.Response[v1.ValidateAccessTicketResponse], error) {
	return c.validateAccessTicket.CallUnary(ctx, req)
}

// CodespaceServiceHandler is an implementation of the codespace.v1.CodespaceService service.
type CodespaceServiceHandler interface {
	// RegisterManager exchanges a scope-bound registration token for a manager
	// identity and manager token.
	RegisterManager(context.Context, *connect.Request[v1.RegisterManagerRequest]) (*connect.Response[v1.RegisterManagerResponse], error)
	// DeclareManager updates the authenticated manager's metadata and runtime
	// capabilities after registration.
	DeclareManager(context.Context, *connect.Request[v1.DeclareManagerRequest]) (*connect.Response[v1.DeclareManagerResponse], error)
	// Ping records the authenticated manager heartbeat and load snapshot.
	Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error)
	// FetchTask leases queued tasks assigned to the authenticated manager.
	FetchTask(context.Context, *connect.Request[v1.FetchTaskRequest]) (*connect.Response[v1.FetchTaskResponse], error)
	// AppendLog appends output to the authenticated manager's active operation.
	AppendLog(context.Context, *connect.Request[v1.AppendLogRequest]) (*connect.Response[v1.AppendLogResponse], error)
	// FinishTask records the authenticated manager's result for a leased task.
	FinishTask(context.Context, *connect.Request[v1.FinishTaskRequest]) (*connect.Response[v1.FinishTaskResponse], error)
	// ReportCodespaceStatus records runtime status for a codespace owned by the
	// authenticated manager.
	ReportCodespaceStatus(context.Context, *connect.Request[v1.ReportCodespaceStatusRequest]) (*connect.Response[v1.ReportCodespaceStatusResponse], error)
	// ReportCodespacePorts replaces the visible port set for a codespace owned
	// by the authenticated manager.
	ReportCodespacePorts(context.Context, *connect.Request[v1.ReportCodespacePortsRequest]) (*connect.Response[v1.ReportCodespacePortsResponse], error)
	// RequestGitToken issues a short-lived repository token for a codespace
	// owned by the authenticated manager.
	RequestGitToken(context.Context, *connect.Request[v1.RequestGitTokenRequest]) (*connect.Response[v1.RequestGitTokenResponse], error)
	// RevokeGitToken revokes active repository tokens for a codespace owned by
	// the authenticated manager.
	RevokeGitToken(context.Context, *connect.Request[v1.RevokeGitTokenRequest]) (*connect.Response[v1.RevokeGitTokenResponse], error)
	// ValidateAccessTicket validates a short-lived user access ticket presented
	// to the gateway.
	ValidateAccessTicket(context.Context, *connect.Request[v1.ValidateAccessTicketRequest]) (*connect.Response[v1.ValidateAccessTicketResponse], error)
}

// NewCodespaceServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCodespaceServiceHandler(svc CodespaceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	codespaceServiceMethods := v1.File_codespace_v1_service_proto.Services().ByName("CodespaceService").Methods()
	codespaceServiceRegisterManagerHandler := connect.NewUnaryHandler(
		CodespaceServiceRegisterManagerProcedure,
		svc.RegisterManager,
		connect.WithSchema(codespaceServiceMethods.ByName("RegisterManager")),
		connect.WithHandlerOptions(opts...),
	)
	codespaceServiceDeclareManagerHandler := connect.NewUnaryHandler(
		CodespaceServiceDeclareManagerProcedure,
		svc.DeclareManager,
		connect.WithSchema(codespaceServiceMethods.ByName("DeclareManager")),
		connect.WithHandlerOptions(opts...),
	)
	codespaceServicePingHandler := connect.NewUnaryHandler(
		CodespaceServicePingProcedure,
		svc.Ping,
		connect.WithSchema(codespaceServiceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	codespaceServiceFetchTaskHandler := connect.NewUnaryHandler(
		CodespaceServiceFetchTaskProcedure,
		svc.FetchTask,
		connect.WithSchema(codespaceServiceMethods.ByName("FetchTask")),
		connect.WithHandlerOptions(opts...),
	)
	codespaceServiceAppendLogHandler := connect.NewUnaryHandler(
		CodespaceServiceAppendLogProcedure,
		svc.AppendLog,
		connect.WithSchema(codespaceServiceMethods.ByName("AppendLog")),
		connect.WithHandlerOptions(opts...),
	)
	codespaceServiceFinishTaskHandler := connect.NewUnaryHandler(
		CodespaceServiceFinishTaskProcedure,
		svc.FinishTask,
		connect.WithSchema(codespaceServiceMethods.ByName("FinishTask")),
		connect.WithHandlerOptions(opts...),
	)
	codespaceServiceReportCodespaceStatusHandler := connect.NewUnaryHandler(
		CodespaceServiceReportCodespaceStatusProcedure,
		svc.ReportCodespaceStatus,
		connect.WithSchema(codespaceServiceMethods.ByName("ReportCodespaceStatus")),
		connect.WithHandlerOptions(opts...),
	)
	codespaceServiceReportCodespacePortsHandler := connect.NewUnaryHandler(
		CodespaceServiceReportCodespacePortsProcedure,
		svc.ReportCodespacePorts,
		connect.WithSchema(codespaceServiceMethods.ByName("ReportCodespacePorts")),
		connect.WithHandlerOptions(opts...),
	)
	codespaceServiceRequestGitTokenHandler := connect.NewUnaryHandler(
		CodespaceServiceRequestGitTokenProcedure,
		svc.RequestGitToken,
		connect.WithSchema(codespaceServiceMethods.ByName("RequestGitToken")),
		connect.WithHandlerOptions(opts...),
	)
	codespaceServiceRevokeGitTokenHandler := connect.NewUnaryHandler(
		CodespaceServiceRevokeGitTokenProcedure,
		svc.RevokeGitToken,
		connect.WithSchema(codespaceServiceMethods.ByName("RevokeGitToken")),
		connect.WithHandlerOptions(opts...),
	)
	codespaceServiceValidateAccessTicketHandler := connect.NewUnaryHandler(
		CodespaceServiceValidateAccessTicketProcedure,
		svc.ValidateAccessTicket,
		connect.WithSchema(codespaceServiceMethods.ByName("ValidateAccessTicket")),
		connect.WithHandlerOptions(opts...),
	)
	return "/codespace.v1.CodespaceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CodespaceServiceRegisterManagerProcedure:
			codespaceServiceRegisterManagerHandler.ServeHTTP(w, r)
		case CodespaceServiceDeclareManagerProcedure:
			codespaceServiceDeclareManagerHandler.ServeHTTP(w, r)
		case CodespaceServicePingProcedure:
			codespaceServicePingHandler.ServeHTTP(w, r)
		case CodespaceServiceFetchTaskProcedure:
			codespaceServiceFetchTaskHandler.ServeHTTP(w, r)
		case CodespaceServiceAppendLogProcedure:
			codespaceServiceAppendLogHandler.ServeHTTP(w, r)
		case CodespaceServiceFinishTaskProcedure:
			codespaceServiceFinishTaskHandler.ServeHTTP(w, r)
		case CodespaceServiceReportCodespaceStatusProcedure:
			codespaceServiceReportCodespaceStatusHandler.ServeHTTP(w, r)
		case CodespaceServiceReportCodespacePortsProcedure:
			codespaceServiceReportCodespacePortsHandler.ServeHTTP(w, r)
		case CodespaceServiceRequestGitTokenProcedure:
			codespaceServiceRequestGitTokenHandler.ServeHTTP(w, r)
		case CodespaceServiceRevokeGitTokenProcedure:
			codespaceServiceRevokeGitTokenHandler.ServeHTTP(w, r)
		case CodespaceServiceValidateAccessTicketProcedure:
			codespaceServiceValidateAccessTicketHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCodespaceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCodespaceServiceHandler struct{}

func (UnimplementedCodespaceServiceHandler) RegisterManager(context.Context, *connect.Request[v1.RegisterManagerRequest]) (*connect.Response[v1.RegisterManagerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codespace.v1.CodespaceService.RegisterManager is not implemented"))
}

func (UnimplementedCodespaceServiceHandler) DeclareManager(context.Context, *connect.Request[v1.DeclareManagerRequest]) (*connect.Response[v1.DeclareManagerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codespace.v1.CodespaceService.DeclareManager is not implemented"))
}

func (UnimplementedCodespaceServiceHandler) Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codespace.v1.CodespaceService.Ping is not implemented"))
}

func (UnimplementedCodespaceServiceHandler) FetchTask(context.Context, *connect.Request[v1.FetchTaskRequest]) (*connect.Response[v1.FetchTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codespace.v1.CodespaceService.FetchTask is not implemented"))
}

func (UnimplementedCodespaceServiceHandler) AppendLog(context.Context, *connect.Request[v1.AppendLogRequest]) (*connect.Response[v1.AppendLogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codespace.v1.CodespaceService.AppendLog is not implemented"))
}

func (UnimplementedCodespaceServiceHandler) FinishTask(context.Context, *connect.Request[v1.FinishTaskRequest]) (*connect.Response[v1.FinishTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codespace.v1.CodespaceService.FinishTask is not implemented"))
}

func (UnimplementedCodespaceServiceHandler) ReportCodespaceStatus(context.Context, *connect.Request[v1.ReportCodespaceStatusRequest]) (*connect.Response[v1.ReportCodespaceStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codespace.v1.CodespaceService.ReportCodespaceStatus is not implemented"))
}

func (UnimplementedCodespaceServiceHandler) ReportCodespacePorts(context.Context, *connect.Request[v1.ReportCodespacePortsRequest]) (*connect.Response[v1.ReportCodespacePortsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codespace.v1.CodespaceService.ReportCodespacePorts is not implemented"))
}

func (UnimplementedCodespaceServiceHandler) RequestGitToken(context.Context, *connect.Request[v1.RequestGitTokenRequest]) (*connect.Response[v1.RequestGitTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codespace.v1.CodespaceService.RequestGitToken is not implemented"))
}

func (UnimplementedCodespaceServiceHandler) RevokeGitToken(context.Context, *connect.Request[v1.RevokeGitTokenRequest]) (*connect.Response[v1.RevokeGitTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codespace.v1.CodespaceService.RevokeGitToken is not implemented"))
}

func (UnimplementedCodespaceServiceHandler) ValidateAccessTicket(context.Context, *connect.Request[v1.ValidateAccessTicketRequest]) (*connect.Response[v1.ValidateAccessTicketResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codespace.v1.CodespaceService.ValidateAccessTicket is not implemented"))
}
